all:
	cd gpudemo && make
	cd gpu3d && make
	cd ping && make
	cd pong && make
	cd wm && make
	cd hello_win && make
	cd draw && make
	cd net && make
	cd term && make
	cd portdemo && make
	cd repl && make
	cd space3d && make

clean:
	cd gpudemo && make clean
	cd gpu3d && make clean
	cd ping && make clean
	cd pong && make clean
	cd wm && make clean
	cd hello_win && make clean
	cd draw && make clean
	cd net && make clean
	cd term && make clean
	cd portdemo && make clean
	cd repl && make clean
	cd space3d && make clean
