/*
 * GENERATED by gen_art.py -- do not edit.
 * Edit art/*.png and re-run it.
 *
 * 1bpp pieces, 96x48, in the framebuffer's bit order (pixel x at bit
 * (x & 7) of byte (x >> 3), least significant bit leftmost) so they
 * can go straight to z_fb_hw_blit_mem() with no repacking.
 *
 * KG_ART_BYTES includes four bytes of padding past the last row --
 * the blitter may read one word beyond what it needs when source and
 * destination are not word-aligned. See gen_art.py.
 */
#ifndef KGART_H
#define KGART_H

#include <stdint.h>

#define KG_ART_W      96
#define KG_ART_H      48
#define KG_ART_STRIDE 12
#define KG_ART_BYTES  (KG_ART_STRIDE * KG_ART_H + 4)

extern const uint8_t kg_art_cat[KG_ART_BYTES];
extern const uint8_t kg_art_crab[KG_ART_BYTES];
extern const uint8_t kg_art_crocodile[KG_ART_BYTES];
extern const uint8_t kg_art_dog[KG_ART_BYTES];
extern const uint8_t kg_art_elephant[KG_ART_BYTES];
extern const uint8_t kg_art_fish[KG_ART_BYTES];
extern const uint8_t kg_art_giraffe[KG_ART_BYTES];
extern const uint8_t kg_art_horse[KG_ART_BYTES];
extern const uint8_t kg_art_kangaroo[KG_ART_BYTES];
extern const uint8_t kg_art_monkey[KG_ART_BYTES];
extern const uint8_t kg_art_owl[KG_ART_BYTES];
extern const uint8_t kg_art_pig[KG_ART_BYTES];
extern const uint8_t kg_art_rabbit[KG_ART_BYTES];
extern const uint8_t kg_art_snake[KG_ART_BYTES];
extern const uint8_t kg_art_spider[KG_ART_BYTES];
extern const uint8_t kg_art_turtle[KG_ART_BYTES];

#endif
