#!/usr/bin/env python3
#
# Zeitlos
# Copyright (c) 2026 Lone Dynamics Corporation. All rights reserved.
#
# Generates synth_tables.h for sw/apps/tts/synth.c:
#
#     python3 gen_tables.py > synth_tables.h
#
# The target is rv32im with no FPU, so everything the synthesiser
# would otherwise compute with cos() and exp() -- resonator
# coefficients -- comes from these tables instead. They are generated
# rather than computed at startup so the service links no libm and no
# soft-float, and so host and target provably use identical numbers.
#
# Pure mathematics: cosines, exponentials and decibels. No speech data.

import math
import sys

FS = 11025        # must match SYNTH_FS in synth.h
COS_N = 1024      # cos(pi * i / COS_N), i = 0..COS_N
BW_STEP = 10      # Hz per entry of the pole-radius table
BW_N = 256        # bandwidths 0 .. 2550 Hz
DB_N = 97         # 0 .. 96 dB
DB_UNITY = 60     # this many dB is 1.0 (Q12, 4096)

def q14(x):
    return int(round(x * 16384))

out = sys.stdout
out.write("/* Generated by gen_tables.py -- do not edit. */\n\n")
out.write("#ifndef SYNTH_TABLES_H\n#define SYNTH_TABLES_H\n\n")
out.write("#include <stdint.h>\n\n")
out.write("#define SYNTH_TABLES_FS %d\n" % FS)
out.write("#define SYNTH_COS_N %d\n" % COS_N)
out.write("#define SYNTH_BW_STEP %d\n" % BW_STEP)
out.write("#define SYNTH_BW_N %d\n" % BW_N)
out.write("#define SYNTH_DB_N %d\n\n" % DB_N)

out.write("// cos(pi * i / SYNTH_COS_N), Q14\n")
out.write("static const int16_t synth_cos[SYNTH_COS_N + 1] = {\n")
vals = [q14(math.cos(math.pi * i / COS_N)) for i in range(COS_N + 1)]
vals = [min(v, 16383) for v in vals]   # 1.0 does not fit in int16 Q14; 16383 is close enough
for i in range(0, len(vals), 12):
    out.write("\t" + ", ".join(str(v) for v in vals[i:i+12]) + ",\n")
out.write("};\n\n")

out.write("// pole radius exp(-pi * bw / FS) for bw = i * SYNTH_BW_STEP, Q14\n")
out.write("static const uint16_t synth_radius[SYNTH_BW_N] = {\n")
vals = [q14(math.exp(-math.pi * i * BW_STEP / FS)) for i in range(BW_N)]
vals = [min(v, 16383) for v in vals]
for i in range(0, len(vals), 12):
    out.write("\t" + ", ".join(str(v) for v in vals[i:i+12]) + ",\n")
out.write("};\n\n")

out.write("// 10^((dB - %d) / 20), Q12 -- %d dB is unity\n" % (DB_UNITY, DB_UNITY))
out.write("static const uint16_t synth_db[SYNTH_DB_N] = {\n")
vals = [0] + [int(round(4096 * 10 ** ((d - DB_UNITY) / 20.0))) for d in range(1, DB_N)]
vals = [min(v, 65535) for v in vals]
for i in range(0, len(vals), 12):
    out.write("\t" + ", ".join(str(v) for v in vals[i:i+12]) + ",\n")
out.write("};\n\n")

out.write("#endif\n")
