/*
 * Zeitlos SOC
 * Copyright (c) 2026 Lone Dynamics Corporation. All rights reserved.
 *
 * GPIO stream engine -- one serial peripheral that can be put on ANY
 * GPIO pin, in one of four modes, chosen at runtime:
 *
 *   1 zlink   8b/10b, self-clocked, 4x oversampled, up to 12 Mbit/s
 *             (docs/zlink.md)
 *   2 spi     SPI master, full duplex, modes 0-3
 *   3 uart    8N1 (or 8N2), 300 baud to 3 Mbaud
 *   4 raw     bits out and/or in at a fixed rate, one per tick
 *
 * rtl/gpio.v instantiates GPIO_STREAM_ENGINES of these (rtl/boards.vh,
 * default 1) and puts their registers at 0xe000_2000 + engine * 0x40.
 * docs/gpio.md has the register map; this header has the reasoning.
 *
 * -- Pins --
 *
 * Four ROLES, each placed on any pin of any port by SPINS:
 *
 *   role 0  TX / MOSI   output
 *   role 1  RX / MISO   input
 *   role 2  CLK / SCK   output (SPI's clock; driven low in other modes)
 *   role 3  CS          output, whatever SCTL.CS says
 *
 * While MODE is not 0, an enabled role OWNS its pin: rtl/gpio.v takes
 * the pin's direction and value from here, and the port's DIR and OUT
 * registers stop reaching it (they still read and write, they just do
 * not drive). IN still reads the pin. Everything else on the port is
 * ordinary GPIO. That is the whole interface to the rest of the chip:
 * this module never touches a pad, so it simulates without a pad model,
 * like gpio.v itself.
 *
 * Any pin, because nothing here uses a pin-specific primitive -- no
 * IDDR, no IOLOGIC, no clock pin. The receiver samples gpio.v's
 * already-synchronised inputs at 48 MHz and does the rest in fabric.
 * That is also the speed limit: 4x oversampling of a 48 MHz sample
 * clock is 12 Mbit/s.
 *
 * -- One block RAM --
 *
 * Both FIFOs live in a single DP16KD in 2048x9 mode: TX in the lower
 * 1024 entries, RX in the upper 1024. Nine bits is a byte plus a K flag
 * (zlink control symbols). The RAM has one write port and one read
 * port, and the CPU and the engine share both, the engine first (see
 * "The FIFO RAM" below for why it is not two ports each). The engine
 * needs a port at most once every 8 clocks, so the CPU rarely waits,
 * and then for one clock.
 *
 * -- Timing --
 *
 * Everything runs on the 48 MHz bus clock, deliberately: the CPU side
 * has to be on it anyway, and a second clock would mean dual-clock
 * FIFOs and synchronised control registers for a 4% faster sample
 * clock (50 MHz) -- or a 100 MHz domain that is hard to close on a full
 * device. To stay off the critical path at 48 MHz, every output is
 * registered, the encoder's result is registered a cycle before it is
 * used (a symbol takes at least 40 clocks, so there is time), and bus
 * reads are registered here and again in gpio.v.
 *
 * -- Bus --
 *
 * gpio.v holds `acc` for as long as an access to this engine is
 * outstanding. This module answers with a one-cycle `done` and the read
 * data in `rdo`, then waits for `acc` to drop before taking another
 * access (st == S_WAIT), so a held strobe can never be taken twice.
 * Plain registers answer in two clocks; STX4 and SRX4 move four FIFO
 * entries through the RAM and take about six. SRX4 pops four entries
 * or none: with fewer than four waiting it reads 0 and leaves the FIFO
 * alone, so software checks the level first (zgpio_stream.c does).
 */

module gpio_stream #(
	parameter NPINS = 8,		// GPIO pins built: NPORTS * 8
	parameter HAS_SPI = 1,
	parameter HAS_UART = 1,
	parameter HAS_RAW = 1
)
(
	input clk,
	input rst,

	input acc,
	input we,
	input [3:0] ra,
	input [31:0] wd,
	output reg done,
	output reg [31:0] rdo,

	input [63:0] pin_in,		// gpio.v's synchronised pins
	output [63:0] own,
	output [63:0] own_dir,
	output [63:0] own_out
);

	// ------------------------------------------------------------------
	// 8b/10b. The case tables come from tools/gen_8b10b.py, which checks
	// the code's properties before writing them; rtl/tests/tb_8b10b.v
	// checks these functions against every symbol that script knows.
	// Symbols are held with bit 'a' in bit 0 (transmission order).
	// ------------------------------------------------------------------

	// -- generated by tools/gen_8b10b.py --verilog; do not edit --
	// 5b/6b, RD- form (bit 0 = a). bit 6 set: unbalanced, so the
	// RD+ form is the complement and the disparity flips. D.07 is
	// balanced but still has two forms (bit 7).
	function [7:0] enc6;
		input [4:0] x;
		case (x)
			5'd0: enc6 = {1'b0, 1'b1, 6'b111001};
			5'd1: enc6 = {1'b0, 1'b1, 6'b101110};
			5'd2: enc6 = {1'b0, 1'b1, 6'b101101};
			5'd3: enc6 = {1'b0, 1'b0, 6'b100011};
			5'd4: enc6 = {1'b0, 1'b1, 6'b101011};
			5'd5: enc6 = {1'b0, 1'b0, 6'b100101};
			5'd6: enc6 = {1'b0, 1'b0, 6'b100110};
			5'd7: enc6 = {1'b1, 1'b0, 6'b000111};
			5'd8: enc6 = {1'b0, 1'b1, 6'b100111};
			5'd9: enc6 = {1'b0, 1'b0, 6'b101001};
			5'd10: enc6 = {1'b0, 1'b0, 6'b101010};
			5'd11: enc6 = {1'b0, 1'b0, 6'b001011};
			5'd12: enc6 = {1'b0, 1'b0, 6'b101100};
			5'd13: enc6 = {1'b0, 1'b0, 6'b001101};
			5'd14: enc6 = {1'b0, 1'b0, 6'b001110};
			5'd15: enc6 = {1'b0, 1'b1, 6'b111010};
			5'd16: enc6 = {1'b0, 1'b1, 6'b110110};
			5'd17: enc6 = {1'b0, 1'b0, 6'b110001};
			5'd18: enc6 = {1'b0, 1'b0, 6'b110010};
			5'd19: enc6 = {1'b0, 1'b0, 6'b010011};
			5'd20: enc6 = {1'b0, 1'b0, 6'b110100};
			5'd21: enc6 = {1'b0, 1'b0, 6'b010101};
			5'd22: enc6 = {1'b0, 1'b0, 6'b010110};
			5'd23: enc6 = {1'b0, 1'b1, 6'b010111};
			5'd24: enc6 = {1'b0, 1'b1, 6'b110011};
			5'd25: enc6 = {1'b0, 1'b0, 6'b011001};
			5'd26: enc6 = {1'b0, 1'b0, 6'b011010};
			5'd27: enc6 = {1'b0, 1'b1, 6'b011011};
			5'd28: enc6 = {1'b0, 1'b0, 6'b011100};
			5'd29: enc6 = {1'b0, 1'b1, 6'b011101};
			5'd30: enc6 = {1'b0, 1'b1, 6'b011110};
			5'd31: enc6 = {1'b0, 1'b1, 6'b110101};
		endcase
	endfunction

	// 3b/4b for data, RD- form (bit 0 = f), same flag layout as
	// enc6. y = 7 here is the primary form; the A7 alternate is
	// chosen by the caller.
	function [5:0] enc4;
		input [2:0] y;
		case (y)
			3'd0: enc4 = {1'b0, 1'b1, 4'b1101};
			3'd1: enc4 = {1'b0, 1'b0, 4'b1001};
			3'd2: enc4 = {1'b0, 1'b0, 4'b1010};
			3'd3: enc4 = {1'b1, 1'b0, 4'b0011};
			3'd4: enc4 = {1'b0, 1'b1, 4'b1011};
			3'd5: enc4 = {1'b0, 1'b0, 4'b0101};
			3'd6: enc4 = {1'b0, 1'b0, 4'b0110};
			3'd7: enc4 = {1'b0, 1'b1, 4'b0111};
		endcase
	endfunction

	// 3b/4b for K28.y when the symbol STARTS at RD- (after the
	// 001111 half); bit 4: unbalanced. From RD+ the whole
	// symbol is the complement.
	function [4:0] enc4k28;
		input [2:0] y;
		case (y)
			3'd0: enc4k28 = {1'b1, 4'b0010};
			3'd1: enc4k28 = {1'b0, 4'b1001};
			3'd2: enc4k28 = {1'b0, 4'b1010};
			3'd3: enc4k28 = {1'b0, 4'b1100};
			3'd4: enc4k28 = {1'b1, 4'b0100};
			3'd5: enc4k28 = {1'b0, 4'b0101};
			3'd6: enc4k28 = {1'b0, 4'b0110};
			3'd7: enc4k28 = {1'b1, 4'b0001};
		endcase
	endfunction

	// 6b/5b decode: {valid, x}. Both RD forms map to the same x.
	function [5:0] dec6;
		input [5:0] s;
		case (s)
			6'd5: dec6 = {1'b1, 5'd15};
			6'd6: dec6 = {1'b1, 5'd0};
			6'd7: dec6 = {1'b1, 5'd7};
			6'd9: dec6 = {1'b1, 5'd16};
			6'd10: dec6 = {1'b1, 5'd31};
			6'd11: dec6 = {1'b1, 5'd11};
			6'd12: dec6 = {1'b1, 5'd24};
			6'd13: dec6 = {1'b1, 5'd13};
			6'd14: dec6 = {1'b1, 5'd14};
			6'd17: dec6 = {1'b1, 5'd1};
			6'd18: dec6 = {1'b1, 5'd2};
			6'd19: dec6 = {1'b1, 5'd19};
			6'd20: dec6 = {1'b1, 5'd4};
			6'd21: dec6 = {1'b1, 5'd21};
			6'd22: dec6 = {1'b1, 5'd22};
			6'd23: dec6 = {1'b1, 5'd23};
			6'd24: dec6 = {1'b1, 5'd8};
			6'd25: dec6 = {1'b1, 5'd25};
			6'd26: dec6 = {1'b1, 5'd26};
			6'd27: dec6 = {1'b1, 5'd27};
			6'd28: dec6 = {1'b1, 5'd28};
			6'd29: dec6 = {1'b1, 5'd29};
			6'd30: dec6 = {1'b1, 5'd30};
			6'd33: dec6 = {1'b1, 5'd30};
			6'd34: dec6 = {1'b1, 5'd29};
			6'd35: dec6 = {1'b1, 5'd3};
			6'd36: dec6 = {1'b1, 5'd27};
			6'd37: dec6 = {1'b1, 5'd5};
			6'd38: dec6 = {1'b1, 5'd6};
			6'd39: dec6 = {1'b1, 5'd8};
			6'd40: dec6 = {1'b1, 5'd23};
			6'd41: dec6 = {1'b1, 5'd9};
			6'd42: dec6 = {1'b1, 5'd10};
			6'd43: dec6 = {1'b1, 5'd4};
			6'd44: dec6 = {1'b1, 5'd12};
			6'd45: dec6 = {1'b1, 5'd2};
			6'd46: dec6 = {1'b1, 5'd1};
			6'd49: dec6 = {1'b1, 5'd17};
			6'd50: dec6 = {1'b1, 5'd18};
			6'd51: dec6 = {1'b1, 5'd24};
			6'd52: dec6 = {1'b1, 5'd20};
			6'd53: dec6 = {1'b1, 5'd31};
			6'd54: dec6 = {1'b1, 5'd16};
			6'd56: dec6 = {1'b1, 5'd7};
			6'd57: dec6 = {1'b1, 5'd0};
			6'd58: dec6 = {1'b1, 5'd15};
			default: dec6 = 6'd0;
		endcase
	endfunction

	// 4b/3b decode for data: {valid, y}. The A7 forms decode to 7.
	function [3:0] dec4;
		input [3:0] s;
		case (s)
			4'd1: dec4 = {1'b1, 3'd7};
			4'd2: dec4 = {1'b1, 3'd0};
			4'd3: dec4 = {1'b1, 3'd3};
			4'd4: dec4 = {1'b1, 3'd4};
			4'd5: dec4 = {1'b1, 3'd5};
			4'd6: dec4 = {1'b1, 3'd6};
			4'd7: dec4 = {1'b1, 3'd7};
			4'd8: dec4 = {1'b1, 3'd7};
			4'd9: dec4 = {1'b1, 3'd1};
			4'd10: dec4 = {1'b1, 3'd2};
			4'd11: dec4 = {1'b1, 3'd4};
			4'd12: dec4 = {1'b1, 3'd3};
			4'd13: dec4 = {1'b1, 3'd0};
			4'd14: dec4 = {1'b1, 3'd7};
			default: dec4 = 4'd0;
		endcase
	endfunction

	// 4b/3b decode for K28.y, from the RD- form of the symbol
	// (001111 ....); the RD+ form is the complement of the whole
	// symbol, so the caller complements first.
	function [3:0] dec4k28;
		input [3:0] s;
		case (s)
			4'b0010: dec4k28 = {1'b1, 3'd0};
			4'b1001: dec4k28 = {1'b1, 3'd1};
			4'b1010: dec4k28 = {1'b1, 3'd2};
			4'b1100: dec4k28 = {1'b1, 3'd3};
			4'b0100: dec4k28 = {1'b1, 3'd4};
			4'b0101: dec4k28 = {1'b1, 3'd5};
			4'b0110: dec4k28 = {1'b1, 3'd6};
			4'b0001: dec4k28 = {1'b1, 3'd7};
			default: dec4k28 = 4'd0;
		endcase
	endfunction
	// -- end generated --

	localparam [9:0] K28_5_N = 10'h17C;	// 0011111010, a first
	localparam [9:0] K28_5_P = 10'h283;	// 1100000101

	// {rd_out, symbol} for (k, byte) at running disparity rd (1 = RD+).
	// Only K28.y and K23/27/29/30.7 are control symbols; zlink uses
	// K28.5 (idle/comma) and K27.7, K29.7, K30.7 (framing, Round 2).
	function [10:0] enc8b10b;
		input k;
		input [7:0] b;
		input rd;
		reg [7:0] e6;
		reg [5:0] e4;
		reg [4:0] e4k;
		reg [5:0] s6;
		reg [3:0] s4;
		reg rd1, rd2, alt;
		begin
			if (k && b[4:0] == 5'd28) begin
				e4k = enc4k28(b[7:5]);
				// 001111 + the RD- 4b half; the whole symbol is
				// complemented from RD+. K28's 6b half is unbalanced, so
				// the disparity flips unless the 4b half flips it back.
				s6 = rd ? 6'b000011 : 6'b111100;
				s4 = rd ? ~e4k[3:0] : e4k[3:0];
				rd2 = rd ^ 1'b1 ^ e4k[4];
			end else begin
				e6 = enc6(b[4:0]);
				s6 = (rd && (e6[6] | e6[7])) ? ~e6[5:0] : e6[5:0];
				rd1 = rd ^ e6[6];
				if (k || b[7:5] == 3'd7) begin
					// Kx.7 always uses the alternate; D.x.7 only for
					// the six (x, rd) pairs that would otherwise make a
					// run of five.
					alt = k ||
						(!rd1 && (b[4:0] == 5'd17 || b[4:0] == 5'd18 ||
						          b[4:0] == 5'd20)) ||
						(rd1 && (b[4:0] == 5'd11 || b[4:0] == 5'd13 ||
						         b[4:0] == 5'd14));
					// A7 0111/1000 and P7 1110/0001, a..j order reversed
					s4 = alt ? (rd1 ? 4'b0001 : 4'b1110)
					         : (rd1 ? 4'b1000 : 4'b0111);
					rd2 = ~rd1;
				end else begin
					e4 = enc4(b[7:5]);
					s4 = (rd1 && (e4[4] | e4[5])) ? ~e4[3:0] : e4[3:0];
					rd2 = rd1 ^ e4[4];
				end
			end
			enc8b10b = { rd2, s4, s6 };
		end
	endfunction

	// {valid, k, byte}
	function [9:0] dec8b10b;
		input [9:0] s;
		reg [5:0] d6;
		reg [3:0] d4;
		reg k28, kx;
		begin
			k28 = (s[5:0] == 6'b111100) || (s[5:0] == 6'b000011);
			if (k28) begin
				d4 = dec4k28(s[5:0] == 6'b111100 ? s[9:6] : ~s[9:6]);
				dec8b10b = { d4[3], 1'b1, d4[2:0], 5'd28 };
			end else begin
				d6 = dec6(s[5:0]);
				d4 = dec4(s[9:6]);
				kx = (d6[4:0] == 5'd23 || d6[4:0] == 5'd27 ||
				      d6[4:0] == 5'd29 || d6[4:0] == 5'd30) &&
				     (s[9:6] == 4'b1110 || s[9:6] == 4'b0001);
				dec8b10b = { d6[5] & d4[3], kx, d4[2:0], d6[4:0] };
			end
		end
	endfunction

	function [7:0] rev8;
		input [7:0] v;
		rev8 = { v[0], v[1], v[2], v[3], v[4], v[5], v[6], v[7] };
	endfunction

	// ------------------------------------------------------------------
	// Registers
	// ------------------------------------------------------------------

	localparam M_OFF = 3'd0, M_ZLINK = 3'd1, M_SPI = 3'd2, M_UART = 3'd3,
	           M_RAW = 3'd4;

	reg [2:0] mode;
	reg lsb, cpha, cpol, txinv, rxinv, txod, rxen, loop, rpt, trig, stop2,
	    cs_lvl, idle_lvl;
	reg [2:0] spidly;
	reg [31:0] spins;
	reg [15:0] div;
	reg lock;			// SLOCK: test-and-set ownership, for zgpio

	wire m_zl   = (mode == M_ZLINK);
	wire m_spi  = HAS_SPI  && (mode == M_SPI);
	wire m_uart = HAS_UART && (mode == M_UART);
	wire m_raw  = HAS_RAW  && (mode == M_RAW);
	wire on     = m_zl | m_spi | m_uart | m_raw;

	wire [31:0] sctl = { 13'd0, spidly, idle_lvl, cs_lvl, stop2, trig, rpt,
	                     loop, rxen, txod, rxinv, txinv, cpol, cpha, lsb,
	                     mode };

	// A mode that this build does not have reads back as off, so
	// software that asks for SPI on a build without it finds out by
	// reading SCTL rather than by nothing happening.
	function [2:0] supported;
		input [2:0] m;
		supported = (m == M_ZLINK) ? m :
		            (m == M_SPI  && HAS_SPI)  ? m :
		            (m == M_UART && HAS_UART) ? m :
		            (m == M_RAW  && HAS_RAW)  ? m : M_OFF;
	endfunction

	// ------------------------------------------------------------------
	// The FIFO RAM: one write port, one read port, both shared
	//
	// Written this way -- one port of each kind, the CPU and the engine
	// taking turns -- because that is what yosys maps to a single
	// DP16KD. Two processes each with a read/write port of their own
	// look like a true dual-port RAM, but yosys cannot drop the write
	// priority it gives two writers of one array, and a true dual-port
	// block RAM has none to give, so it falls back to flip-flops:
	// 18,432 of them, and the build no longer fits. (rtl/tests has no
	// test for this; docs/gpio.md's utilisation table is the check.)
	//
	// The engine always wins a port: its accesses are at most one every
	// 8 clocks (raw at full rate) and must not be late, while the CPU's
	// can wait a clock without anyone noticing. The two never touch the
	// same address in the same cycle -- the engine reads TX entries the
	// CPU has finished writing, and the CPU reads RX entries the engine
	// has finished writing -- so the RAM's read-during-write behaviour
	// never matters.
	// ------------------------------------------------------------------

	reg [8:0] mem [0:2047];

	// 11-bit pointers over 1024 entries: the top bit tells full from
	// empty, and the difference is the level directly.
	reg [10:0] txw, txr, rxw, rxr, loop_start;
	wire [10:0] tx_level = txw - txr;
	wire [10:0] rx_level = rxw - rxr;
	wire tx_full = tx_level[10];
	wire rx_full = rx_level[10];

	reg [8:0] tx_byte;		// next entry for the datapath
	reg tx_have;
	reg tx_take;			// datapath consumed tx_byte this clock
	reg fpend, f1;
	reg fkill;				// a flush landed while a fetch was in flight

	reg rx_push;			// datapath has a byte for the RX FIFO
	reg [8:0] rx_pdata;

	reg flush_tx;

	// the engine's two kinds of access
	wire e_w = rx_push && !rx_full;
	wire e_r = on && !tx_have && !fpend && !flush_tx &&
	           (tx_level != 11'd0) && !tx_take;

	// the CPU's, granted when the engine is not using that port
	wire cw_req, cr_req;
	reg [8:0] cw_data;
	wire cw_go = cw_req && !e_w;
	wire cr_go = cr_req && !e_r;

	wire [10:0] w_addr = e_w ? { 1'b1, rxw[9:0] } : { 1'b0, txw[9:0] };
	wire [8:0]  w_data = e_w ? rx_pdata : cw_data;
	wire [10:0] r_addr = e_r ? { 1'b0, txr[9:0] } : { 1'b1, rxr[9:0] };
	reg  [8:0]  r_q;

	always @(posedge clk) begin
		if (e_w || cw_go) mem[w_addr] <= w_data;
	end

	always @(posedge clk) begin
		r_q <= mem[r_addr];
	end

	// sticky status
	reg txovf, rxovr, kword, aligned;
	reg [15:0] serr;
	reg err_inc;

	// ------------------------------------------------------------------
	// CPU side
	// ------------------------------------------------------------------

	localparam S_IDLE = 2'd0, S_PUSH = 2'd1, S_POP = 2'd2, S_WAIT = 2'd3;
	reg [1:0] st;
	reg [31:0] stage;
	reg stk;				// STX: the K flag of the one byte
	reg [2:0] pcnt;			// entries left to write / to read
	reg [2:0] pgot;			// entries received
	reg cr_d;				// a CPU read was issued last clock
	reg pop4;

	reg sctl_wr;			// datapath reset on a MODE change

	assign cw_req = (st == S_PUSH) && (pcnt != 3'd0) && !tx_full;
	assign cr_req = (st == S_POP) && (pcnt != 3'd0);

	always @(*) cw_data = { stk, stage[7:0] };

	wire busy;
	wire [31:0] sstat = { 5'd0, rx_level, kword, aligned, txovf, rxovr,
	                      busy, tx_level };

	// Everything a plain register read can return, in ONE multiplexer.
	// rdo is loaded from it, from the FIFO path below, and nowhere
	// else: written as a case per assignment site, yosys builds a 32-bit
	// mux chain for each, which was a few hundred LUT4 of nothing.
	reg [31:0] rmux;
	always @(*) begin
		case (ra)
		4'd0: rmux = sctl;
		4'd1: rmux = spins;
		4'd2: rmux = { 16'd0, div };
		4'd3: rmux = sstat;
		4'd8: rmux = { 16'd0, serr };
		4'd10: rmux = { 31'd0, lock };
		default: rmux = 32'd0;
		endcase
	end

	// SRX pops one entry if there is one; SRX4 pops four, and only when
	// there ARE four -- otherwise it reads 0 and pops nothing, and
	// software (zgpio_stream.c) checks the level first, so a short pop
	// never needs the bytes realigning in hardware.
	wire pop1 = (ra == 4'd6) && (rx_level != 11'd0);
	wire popq = (ra == 4'd7) && (rx_level >= 11'd4);

	always @(posedge clk) begin
		done <= 1'b0;
		sctl_wr <= 1'b0;
		flush_tx <= 1'b0;
		cr_d <= cr_go;

		if (rst) begin
			st <= S_IDLE;
			mode <= M_OFF;
			{ lsb, cpha, cpol, txinv, rxinv, txod, rxen, loop, rpt,
			  trig, stop2, cs_lvl, idle_lvl } <= 13'd0;
			spidly <= 3'd0;
			spins <= 32'd0;
			div <= 16'd0;
			lock <= 1'b0;
			txw <= 11'd0;
			rxr <= 11'd0;
			txovf <= 1'b0;
			kword <= 1'b0;
			rdo <= 32'd0;
			pcnt <= 3'd0;
		end else begin
			if (cw_go) txw <= txw + 11'd1;
			if (cr_go) rxr <= rxr + 11'd1;

			case (st)

			S_IDLE: if (acc) begin
				if (we) begin
					case (ra)
					4'd0: begin
						sctl_wr <= (supported(wd[2:0]) != mode);
						mode <= supported(wd[2:0]);
						lsb <= wd[3];   cpha <= wd[4];  cpol <= wd[5];
						txinv <= wd[6]; rxinv <= wd[7]; txod <= wd[8];
						rxen <= wd[9];  loop <= wd[10]; rpt <= wd[11];
						trig <= wd[12]; stop2 <= wd[13]; cs_lvl <= wd[14];
						idle_lvl <= wd[15]; spidly <= wd[18:16];
					end
					4'd1: spins <= wd;
					4'd2: div <= wd[15:0];
					4'd9: begin
						flush_tx <= wd[0];
						if (wd[1]) rxr <= rxw;
						if (wd[2]) begin
							txovf <= 1'b0;
							kword <= 1'b0;
						end
					end
					4'd10: lock <= wd[0];
					default: ;
					endcase
					if (ra == 4'd4 || ra == 4'd5) begin
						// STX: one entry, K flag and all. STX4: four
						// data bytes, byte 0 first.
						stage <= wd;
						stk <= (ra == 4'd4) ? wd[8] : 1'b0;
						pcnt <= (ra == 4'd4) ? 3'd1 : 3'd4;
						st <= S_PUSH;
					end else begin
						done <= 1'b1;
						st <= S_WAIT;
					end
				end else begin
					if (ra == 4'd10) lock <= 1'b1;	// SLOCK: test-and-set
					if (pop1 || popq) begin
						pop4 <= popq;
						pcnt <= popq ? 3'd4 : 3'd1;
						pgot <= 3'd0;
						rdo <= 32'd0;
						st <= S_POP;
					end else begin
						// SLOCK reads the lock as it was before this read
						// took it: rmux sees the old value this clock
						rdo <= rmux;
						done <= 1'b1;
						st <= S_WAIT;
					end
				end
			end

			// One entry a clock, whenever the write port is ours. A full
			// FIFO drops the entry and says so in TXOVF.
			S_PUSH: begin
				if (pcnt == 3'd0) begin
					done <= 1'b1;
					st <= S_WAIT;
				end else if (tx_full || cw_go) begin
					if (tx_full) txovf <= 1'b1;
					stage <= { 8'd0, stage[31:8] };
					stk <= 1'b0;
					pcnt <= pcnt - 3'd1;
				end
			end

			// One read issued a clock, whenever the read port is ours;
			// each lands in r_q the clock after.
			S_POP: begin
				if (cr_go) pcnt <= pcnt - 3'd1;
				if (cr_d) begin
					// SRX4 shifts each byte in from the top, so after four
					// the first one is in bits 7:0
					if (pop4) begin
						rdo <= { r_q[7:0], rdo[31:8] };
						if (r_q[8]) kword <= 1'b1;
					end else
						rdo <= { 22'd0, 1'b1, r_q };
					pgot <= pgot + 3'd1;
					if (pgot + 3'd1 == (pop4 ? 3'd4 : 3'd1)) begin
						done <= 1'b1;
						st <= S_WAIT;
					end
				end
			end

			S_WAIT: if (!acc) st <= S_IDLE;

			endcase
		end
	end

	// ------------------------------------------------------------------
	// Engine side: the TX prefetch and the RX push
	// ------------------------------------------------------------------

	// a MODE change or MODE = 0 resets the datapath, not the FIFOs
	wire dp_rst = rst || sctl_wr || !on;

	// Pins are taken only once the datapath reset has run with the NEW
	// mode, one clock after MODE is written. Without this, the clock in
	// which MODE first reads non-zero still has the old mode's idle
	// level in the shift register, and the TX pin glitches -- low, for a
	// raw or UART line that should idle high -- which a receiver at the
	// other end takes for a start bit or a trigger edge.
	reg live;
	always @(posedge clk) live <= on && !dp_rst;

	always @(posedge clk) begin
		f1 <= 1'b0;

		if (rst) begin
			txr <= 11'd0;
			rxw <= 11'd0;
			loop_start <= 11'd0;
			tx_have <= 1'b0;
			fpend <= 1'b0;
			fkill <= 1'b0;
			rxovr <= 1'b0;
		end else begin
			if (tx_take) tx_have <= 1'b0;

			if (st == S_IDLE && acc && we && ra == 4'd9 && wd[1])
				rxovr <= 1'b0;

			if (rx_push) begin
				if (rx_full) rxovr <= 1'b1;
				else rxw <= rxw + 11'd1;
			end

			if (e_r) begin
				txr <= txr + 11'd1;
				fpend <= 1'b1;
				f1 <= 1'b1;
			end else if (on && !tx_have && !fpend && !flush_tx &&
			             tx_level == 11'd0 && rpt && m_raw &&
			             txr != loop_start) begin
				// raw repeat: the FIFO ran dry, so go round again
				txr <= loop_start;
			end

			if (f1) begin
				if (!fkill) begin
					tx_byte <= r_q;
					tx_have <= 1'b1;
				end
				fpend <= 1'b0;
				fkill <= 1'b0;
			end

			if (flush_tx) begin
				txr <= txw;
				loop_start <= txw;
				tx_have <= 1'b0;
				if (fpend) fkill <= 1'b1;
			end
			// arming repeat marks where the loop starts
			if (sctl_wr) loop_start <= txr;
		end
	end

	// ------------------------------------------------------------------
	// Tick: the 48 MHz clock divided by DIV + 1. zlink and UART spend 4
	// ticks a bit, SPI 2 (one per SCK edge), raw 1.
	// ------------------------------------------------------------------

	reg [15:0] tcnt;
	wire tick = on && (tcnt == 16'd0);

	always @(posedge clk) begin
		if (dp_rst) tcnt <= 16'd0;
		else tcnt <= tick ? div : tcnt - 16'd1;
	end

	// ------------------------------------------------------------------
	// Pins
	// ------------------------------------------------------------------

	wire en_tx  = spins[7],  en_rx  = spins[15];
	wire en_clk = spins[23], en_cs  = spins[31];
	wire [5:0] p_tx  = spins[5:0],   p_rx  = spins[13:8];
	wire [5:0] p_clk = spins[21:16], p_cs  = spins[29:24];

	reg [10:0] txsh;
	reg mosi_r, sck_r;
	reg sp_act;
	reg [4:0] sp_e;
	reg [7:0] sp_tx, sp_rx;
	reg [2:0] sp_rn;

	wire tx_line = m_spi ? mosi_r : txsh[0];
	wire tx_lvl = tx_line ^ txinv;

	wire rx_pin = pin_in[p_rx];
	wire rx_line = loop ? tx_line : (rx_pin ^ rxinv);

	genvar gp;
	generate
		for (gp = 0; gp < 64; gp = gp + 1) begin : pins
			if (gp < NPINS) begin : built
				wire h_tx  = en_tx  && (p_tx  == gp);
				wire h_rx  = en_rx  && (p_rx  == gp);
				wire h_clk = en_clk && (p_clk == gp);
				wire h_cs  = en_cs  && (p_cs  == gp);
				assign own[gp] = live && (h_tx | h_rx | h_clk | h_cs);
				// TX > CLK > CS > RX if two roles name one pin, which
				// software should never do (zgpio refuses it)
				assign own_dir[gp] = h_tx ? (txod ? !tx_lvl : 1'b1) :
				                     (h_clk | h_cs);
				assign own_out[gp] = h_tx ? (txod ? 1'b0 : tx_lvl) :
				                     h_clk ? (m_spi & sck_r) :
				                     h_cs ? cs_lvl : 1'b0;
			end else begin : none
				assign own[gp] = 1'b0;
				assign own_dir[gp] = 1'b0;
				assign own_out[gp] = 1'b0;
			end
		end
	endgenerate

	// ------------------------------------------------------------------
	// TX: zlink, UART and raw share one shift register
	// ------------------------------------------------------------------

	reg [3:0] txleft;
	reg [1:0] tph;
	reg rd;					// zlink running disparity, 1 = RD+
	reg [10:0] enc_q;		// next symbol, encoded a clock early
	reg enc_data;			// enc_q is a FIFO entry, not an idle comma
	reg [7:0] zl_run;		// data symbols since the last comma
	reg tx_act;				// a data frame is on the wire

	wire bit_end = tick && (m_raw || tph == 2'd3);

	// The encoder's input: the next FIFO entry, or K28.5 when there is
	// none -- and K28.5 anyway after 255 data symbols in a row, so a
	// receiver that slips a bit in a long burst finds its alignment
	// again within 256 symbols rather than at the end of the burst.
	wire enc_is_data = tx_have && (zl_run != 8'd255);

	always @(posedge clk) begin
		enc_q <= enc8b10b(enc_is_data ? tx_byte[8] : 1'b1,
		                  enc_is_data ? tx_byte[7:0] : 8'hBC, rd);
		enc_data <= enc_is_data;
	end

	// SPI starts a byte -- and so consumes tx_byte -- on the same
	// condition its own block uses below.
	wire sp_room = !rxen || (rx_level < 11'd1020);
	wire sp_take = m_spi && tick && !sp_act && tx_have && !tx_take &&
	               sp_room;

	always @(posedge clk) begin
		tx_take <= 1'b0;
		if (sp_take && !dp_rst) tx_take <= 1'b1;
		if (dp_rst) begin
			txsh <= { 11{ m_uart | (m_raw & idle_lvl) } };
			txleft <= 4'd0;
			tph <= 2'd0;
			rd <= 1'b0;
			zl_run <= 8'd0;
			tx_act <= 1'b0;
		end else if (!m_spi) begin
			if (tick) tph <= m_raw ? 2'd0 : tph + 2'd1;
			if (bit_end) begin
				if (txleft > 4'd1) begin
					txsh <= { txsh[10], txsh[10:1] };
					txleft <= txleft - 4'd1;
				end else if (m_zl) begin
					txsh <= { 1'b0, enc_q[9:0] };
					rd <= enc_q[10];
					txleft <= 4'd10;
					tx_act <= enc_data;
					if (enc_data) begin
						tx_take <= 1'b1;
						zl_run <= zl_run + 8'd1;
					end else
						zl_run <= 8'd0;
				end else if (tx_have && !tx_take) begin
					tx_take <= 1'b1;
					tx_act <= 1'b1;
					if (m_uart) begin
						// LSB first: start, eight data bits, stop(s)
						txsh <= { 2'b11, tx_byte[7:0], 1'b0 };
						txleft <= stop2 ? 4'd11 : 4'd10;
					end else begin
						txsh <= { 3'd0, lsb ? tx_byte[7:0] : rev8(tx_byte[7:0]) };
						txleft <= 4'd8;
					end
				end else begin
					// nothing to send: hold the idle level for a bit
					txsh <= { 11{ m_uart | idle_lvl } };
					txleft <= 4'd1;
					tx_act <= 1'b0;
				end
			end
		end
	end

	// ------------------------------------------------------------------
	// SPI master
	//
	// SCK toggles once per tick, so its half-period is DIV + 1 clocks:
	// 48 MHz / (2 * (DIV + 1)). Bytes go out MSB first unless LSB is
	// set (handled by reversing on the way in and out). MISO is read
	// SPIDLY clocks after the sampling edge's strobe; with SPIDLY = 0
	// that is the pin as it was just BEFORE the edge, which is what a
	// device expects (see docs/gpio.md, "SPI timing").
	// ------------------------------------------------------------------

	reg sp_strobe;
	reg [7:0] sp_pipe;

	always @(posedge clk) begin
		sp_strobe <= 1'b0;
		if (dp_rst || !m_spi) begin
			sp_act <= 1'b0;
			sp_e <= 5'd0;
			sck_r <= cpol;
			sp_pipe <= 8'd0;
			sp_rn <= 3'd0;
		end else begin
			sp_pipe <= { sp_pipe[6:0], sp_strobe };
			if (tick) begin
				if (!sp_act) begin
					sck_r <= cpol;
					if (tx_have && !tx_take && sp_room) begin
						sp_act <= 1'b1;
						sp_e <= 5'd0;
						if (!cpha) begin
							mosi_r <= lsb ? tx_byte[0] : tx_byte[7];
							sp_tx <= (lsb ? rev8(tx_byte[7:0]) : tx_byte[7:0]) << 1;
						end else
							sp_tx <= lsb ? rev8(tx_byte[7:0]) : tx_byte[7:0];
					end
				end else begin
					sck_r <= ~sck_r;
					sp_e <= sp_e + 5'd1;
					if (!sp_e[0]) begin
						// leading edge (1st, 3rd, ... 15th)
						if (cpha) begin
							mosi_r <= sp_tx[7];
							sp_tx <= sp_tx << 1;
						end else
							sp_strobe <= 1'b1;
					end else begin
						// trailing edge
						if (cpha)
							sp_strobe <= 1'b1;
						else if (sp_e != 5'd15) begin
							mosi_r <= sp_tx[7];
							sp_tx <= sp_tx << 1;
						end
					end
					if (sp_e == 5'd15) sp_act <= 1'b0;
				end
			end
			if (sp_pipe[spidly]) begin
				sp_rx <= { sp_rx[6:0], rx_line };
				sp_rn <= sp_rn + 3'd1;
			end
		end
	end

	// SPI consumes tx_byte when it starts a byte (the TX block above
	// owns tx_take and ORs this in)

	// ------------------------------------------------------------------
	// RX: zlink, UART and raw
	// ------------------------------------------------------------------

	reg rprev;
	reg [1:0] rph;
	reg [9:0] rx10;
	reg [3:0] rbit;
	reg [9:0] sym_q;
	reg sym_v;

	reg ur_busy;
	reg [1:0] ur_ph;
	reg [3:0] ur_n;
	reg [7:0] ur_sr;

	reg rr_wait;
	reg [2:0] rr_n;
	reg [7:0] rr_sr;

	// next phase of the sample being taken: an edge restarts the bit
	wire [1:0] ph_now = (rx_line != rprev) ? 2'd0 : rph + 2'd1;
	wire [9:0] rx10n = { rx_line, rx10[9:1] };
	wire is_comma = (rx10n == K28_5_N) || (rx10n == K28_5_P);
	wire [9:0] dsym = dec8b10b(sym_q);
	wire [7:0] rr_next = lsb ? { rx_line, rr_sr[7:1] } : { rr_sr[6:0], rx_line };

	always @(posedge clk) begin
		rx_push <= 1'b0;
		err_inc <= 1'b0;

		if (dp_rst) begin
			// All ones, not whatever the last run left: stale bits plus
			// the first new sample can complete a false comma and align
			// the receiver off the symbol boundary. With ones in front, a
			// match needs the received bits to BE the tail of a real
			// K28.5, since only a comma has five equal bits in a row.
			rx10 <= 10'h3FF;
			rprev <= rx_line;
			rph <= 2'd0;
			rbit <= 4'd0;
			sym_v <= 1'b0;
			aligned <= 1'b0;
			ur_busy <= 1'b0;
			rr_wait <= trig;
			rr_n <= 3'd0;
		end else begin

			// zlink: re-time on every edge, sample at phase 2
			if (m_zl && tick) begin
				rprev <= rx_line;
				rph <= ph_now;
				if (ph_now == 2'd2) begin
					rx10 <= rx10n;
					if (is_comma) begin
						// a comma off the symbol boundary is an error,
						// but it is also the new boundary
						if (aligned && rbit != 4'd9) err_inc <= 1'b1;
						aligned <= 1'b1;
						rbit <= 4'd0;
					end else if (aligned) begin
						if (rbit == 4'd9) begin
							sym_q <= rx10n;
							sym_v <= 1'b1;
							rbit <= 4'd0;
						end else
							rbit <= rbit + 4'd1;
					end
				end
			end

			// decode a clock later, off the sampling path
			if (sym_v) begin
				sym_v <= 1'b0;
				if (dsym[9]) begin
					rx_pdata <= dsym[8:0];
					rx_push <= rxen;
				end else begin
					// not a symbol: count it and wait for the next comma
					err_inc <= 1'b1;
					aligned <= 1'b0;
				end
			end

			// UART: start bit found on a low sample, checked at its
			// middle (phase 1 -> 2 ticks in), then a bit every 4 ticks
			if (m_uart && tick) begin
				if (!ur_busy) begin
					if (!rx_line) begin
						ur_busy <= 1'b1;
						ur_ph <= 2'd0;
						ur_n <= 4'd0;
					end
				end else begin
					ur_ph <= ur_ph + 2'd1;
					if (ur_ph == 2'd1) begin
						if (ur_n == 4'd0) begin
							if (rx_line) ur_busy <= 1'b0;	// a glitch
							else ur_n <= 4'd1;
						end else if (ur_n <= 4'd8) begin
							ur_sr <= { rx_line, ur_sr[7:1] };
							ur_n <= ur_n + 4'd1;
						end else begin
							ur_busy <= 1'b0;
							if (rx_line) begin
								rx_pdata <= { 1'b0, ur_sr };
								rx_push <= rxen;
							end else
								err_inc <= 1'b1;		// framing
						end
					end
				end
			end

			// raw: a bit every tick, optionally from the first edge
			if (m_raw && tick && rxen) begin
				rprev <= rx_line;
				if (rr_wait) begin
					if (rx_line != rprev) begin
						rr_wait <= 1'b0;
						rr_sr <= rr_next;
						rr_n <= 3'd1;
					end
				end else begin
					rr_sr <= rr_next;
					rr_n <= rr_n + 3'd1;
					if (rr_n == 3'd7) begin
						rx_pdata <= { 1'b0, rr_next };
						rx_push <= 1'b1;
					end
				end
			end

			// SPI: a byte every eight samples
			if (m_spi && sp_pipe[spidly] && sp_rn == 3'd7) begin
				rx_pdata <= { 1'b0, lsb ? rev8({ sp_rx[6:0], rx_line })
				                        : { sp_rx[6:0], rx_line } };
				rx_push <= rxen;
			end
		end
	end

	// zlink is aligned in SSTAT; the other modes report 0
	always @(posedge clk) begin
		if (rst) serr <= 16'd0;
		else if (st == S_IDLE && acc && we && ra == 4'd9 && wd[2])
			serr <= 16'd0;
		else if (err_inc && serr != 16'hFFFF) serr <= serr + 16'd1;
	end

	assign busy = (tx_level != 11'd0) || tx_have || tx_act || sp_act ||
	              (sp_pipe != 8'd0);

endmodule
