#
# Zeitlos release tooling -- generated files, and getting rid of them.
#
# A release build has to put two things into the source tree that do
# not belong there:
#
#   rtl/zspec.vh              the composed define set for one target
#   boards/<target>.lpf       base .lpf plus any PMOD fragments
#
# Both are transient. Leaving either behind is not a cosmetic problem:
# a stale rtl/zspec.vh is invisible to `make BOARD=lakritz flash`
# (nothing defines ZSPEC, so boards.vh never includes it) but it WILL
# be picked up by the next release build for a different target if that
# build crashes before writing its own -- and a leftover
# boards/lakritz_langkatze.lpf is a file that looks hand-written and
# checked-in when it is neither.
#
# So every generated file is tracked in a manifest on disk,
# release/.generated, written BEFORE the file itself. Three layers of
# cleanup, in order of how much has gone wrong:
#
#   1. Normal path: the context manager's __exit__ removes them.
#   2. Crash / SIGINT: __exit__ still runs for exceptions, and the
#      manifest survives a hard kill.
#   3. Hard kill (SIGKILL, power loss): the NEXT invocation of any
#      zrelease command reads the manifest and cleans up first, before
#      doing anything else. `zrelease clean` does the same on demand.
#
# The manifest records a hash of what was written, and cleanup refuses
# to delete a tracked path whose contents have changed since -- on the
# theory that if you have edited it, you meant to, and losing that is
# worse than leaving a stray file behind.
#

import hashlib
import json
import os

MANIFEST = "release/.generated"


def _sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def _load_manifest(root):
    path = os.path.join(root, MANIFEST)
    if not os.path.exists(path):
        return []
    try:
        with open(path) as f:
            return json.load(f)
    except (ValueError, OSError):
        return []


def _save_manifest(root, entries):
    path = os.path.join(root, MANIFEST)
    if not entries:
        if os.path.exists(path):
            os.unlink(path)
        return
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(entries, f, indent=1)


def sweep(root, verbose=True):
    """Remove anything a previous run generated and left behind.

    Safe to call at any time, including when nothing is outstanding.
    Called at the start of every zrelease command.
    """
    entries = _load_manifest(root)
    kept = []
    removed = []
    for e in entries:
        path = os.path.join(root, e["path"])
        if not os.path.exists(path):
            continue
        try:
            current = _sha(path)
        except OSError:
            current = None
        if current is not None and current != e.get("sha"):
            # Somebody edited it. Do not throw that away.
            kept.append(e)
            if verbose:
                print("  keeping %s -- modified since it was generated "
                      "(delete it by hand if that was not deliberate)"
                      % e["path"])
            continue
        os.unlink(path)
        removed.append(e["path"])

    _save_manifest(root, kept)
    if verbose and removed:
        for p in removed:
            print("  removed generated %s" % p)
    return removed, kept


class Generated:
    """Context manager owning the files written into the source tree.

    with Generated(root) as g:
        g.write("rtl/zspec.vh", text)
        ... build ...
    # files are gone here, however the block exited
    """

    def __init__(self, root, keep=False):
        self.root = root
        self.keep = keep
        self.entries = []

    def __enter__(self):
        return self

    def write(self, relpath, text):
        path = os.path.join(self.root, relpath)
        if os.path.exists(path) and not self._is_ours(relpath):
            raise RuntimeError(
                "%s already exists and was not generated by this tool. "
                "Refusing to overwrite it -- move it aside first." % relpath)

        # Manifest first, file second. If we die between the two, the
        # next sweep() looks for a file that is not there and moves on;
        # the other order would leave an untracked file behind forever.
        entry = {"path": relpath, "sha": None}
        self.entries.append(entry)
        self._persist()

        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(text)
        entry["sha"] = _sha(path)
        self._persist()
        return path

    def _is_ours(self, relpath):
        return any(e["path"] == relpath for e in _load_manifest(self.root))

    def _persist(self):
        existing = [e for e in _load_manifest(self.root)
                    if e["path"] not in {x["path"] for x in self.entries}]
        _save_manifest(self.root, existing + self.entries)

    def release(self):
        """Drop the files, quietly. Idempotent."""
        for e in list(self.entries):
            path = os.path.join(self.root, e["path"])
            if os.path.exists(path):
                try:
                    if _sha(path) != e["sha"]:
                        print("  keeping %s -- modified during the build"
                              % e["path"])
                        continue
                except OSError:
                    pass
                os.unlink(path)
        remaining = [e for e in _load_manifest(self.root)
                     if e["path"] not in {x["path"] for x in self.entries}]
        _save_manifest(self.root, remaining)
        self.entries = []

    def __exit__(self, exc_type, exc, tb):
        if self.keep:
            print("\n  --keep-generated: leaving these in the tree:")
            for e in self.entries:
                print("    %s" % e["path"])
            print("  run `zrelease clean` before using the normal build.")
            return False
        self.release()
        return False


# ---------------------------------------------------------------------
# The generated content itself
# ---------------------------------------------------------------------

def zspec_vh(target, version, commit):
    """The board-config half of rtl/boards.vh, for one target."""
    lines = [
        "// GENERATED FILE -- DO NOT EDIT, DO NOT COMMIT.",
        "//",
        "// Written by release/zrelease and deleted again when the build",
        "// finishes. rtl/boards.vh includes this INSTEAD OF its own",
        "// per-board `ifdef chain when ZSPEC is defined, which is why a",
        "// release build can express the absence of a feature and a",
        "// command-line -D cannot.",
        "//",
        "// target:  %s" % target.name,
        "// board:   %s" % target.board,
        "// spec:    %s" % ", ".join(
            os.path.relpath(s) for s in target.sources),
        "// version: %s" % version,
        "// commit:  %s" % commit,
        "//",
        "// If you are reading this in a checked-out tree, a release build",
        "// died without cleaning up. `release/zrelease clean` removes it,",
        "// and nothing else in the tree depends on it.",
        "",
    ]
    for name, val in target.defines.items():
        if val is None:
            lines.append("`define %s" % name)
        else:
            lines.append("`define %s %s" % (name, val))
    lines.append("")
    return "\n".join(lines)


import re

# LOCATE COMP "NAME" SITE "BALL";
_LOCATE = re.compile(r'^\s*LOCATE\s+COMP\s+"([^"]+)"\s+SITE\s+"([^"]+)"',
                     re.I)


def _locates(text):
    """[(port, site, lineno)] for the uncommented LOCATE lines."""
    out = []
    for n, line in enumerate(text.splitlines(), 1):
        if line.lstrip().startswith("#"):
            continue
        m = _LOCATE.match(line)
        if m:
            out.append((m.group(1), m.group(2), n))
    return out


def check_site_conflicts(pieces):
    """Two ports on one ball is a hard error. Find it here, not in nextpnr.

    `pieces` is [(label, text)] in merge order.

    Worth doing here rather than leaving to place-and-route for two
    reasons. nextpnr's message names the site and the second port but
    not the first, nor which file each came from -- and with a base
    .lpf plus one or more PMOD fragments, "which file" is the actual
    question. And a PMOD conflicting with something already on the
    board is not an exotic failure, it is the normal consequence of a
    connector being shared: the whole reason a target spec can REMOVE a
    define is that a PMOD sometimes displaces an on-board peripheral.
    """
    seen = {}
    problems = []
    for label, text in pieces:
        for port, site, lineno in _locates(text):
            if site in seen:
                oport, olabel, oline = seen[site]
                if oport == port:
                    continue        # same port constrained twice; harmless
                problems.append(
                    "ball %s is claimed by both '%s' (%s:%d) and '%s' "
                    "(%s:%d)" % (site, oport, olabel, oline, port, label,
                                 lineno))
            else:
                seen[site] = (port, label, lineno)
    return problems


def _drop_constraints(text, claimed_balls, extra_ports):
    """Comment out constraints a PMOD has taken over.

    Two reasons a line goes:

      - its ball belongs to an occupied PMOD port, so whatever the
        board put there was assuming a different PMOD
      - the target named the port explicitly in lpf_drop

    Returns (text, [(port_name, reason)]).
    """
    dropped = {}
    port_of_ball = {}
    for port, site, _ in _locates(text):
        port_of_ball.setdefault(port, site)

    def reason_for(port):
        if port in extra_ports:
            return "named in lpf_drop"
        ball = port_of_ball.get(port)
        if ball in claimed_balls:
            return "%s is %s" % (ball, claimed_balls[ball])
        return None

    out = []
    for line in text.splitlines():
        s2 = line.lstrip()
        hit = None
        if not s2.startswith("#"):
            m = _LOCATE.match(line)
            if m:
                hit = m.group(1)
            else:
                m2 = re.match(r'^\s*IOBUF\s+PORT\s+"([^"]+)"', line, re.I)
                if m2:
                    hit = m2.group(1)
        why = reason_for(hit) if hit else None
        if why:
            dropped[hit] = why
            out.append("# released (%s): %s" % (why, line.strip()))
        else:
            out.append(line)
    return "\n".join(out), sorted(dropped.items())


def merged_lpf(root, target):
    """The board .lpf with PMOD ports rewired, or None if nothing changes.

    A PMOD spec says what each PMOD PIN does; a board spec says which
    BALL each pin of each port is. This puts the two together, so a
    PMOD is described once and works on any board that declares a port.

    THE PORT IS TAKEN OVER WHOLESALE. Every constraint in the base .lpf
    landing on a ball belonging to an occupied port is commented out
    before the PMOD's own are added. That is not a workaround, it is
    the correct reading of what a board .lpf says: boards/lakritz_v0.lpf
    puts UART0_TX on B12 and UART0_RX on B13, which are PMOD_A2 and
    PMOD_A3, so it has been assuming a USB-UART PMOD in port A all
    along. Plugging in a Langkatze instead makes that assumption false,
    and the constraints that encoded it have to go with it.

    Which is also why lakritz_uart regenerates byte-identical pins to
    the plain board build: the usbuart spec puts UART0_TX back on pin 2
    and UART0_RX back on pin 3 of the same port. check_lpf_equivalence()
    asserts exactly that.
    """
    if not target.pmods and not target.lpf_drop:
        return None, None

    base_rel = "boards/" + target.lpf
    with open(os.path.join(root, base_rel)) as f:
        base_text = f.read()

    # Balls claimed by every occupied port, and the ports themselves.
    claimed = {}                      # ball -> "port a pin 2"
    for pm in target.pmods:
        for pin, ball in target.pmod_ports[pm.port].items():
            claimed[ball] = "port %s pin %d" % (pm.port, pin)

    base_text, dropped = _drop_constraints(base_text, claimed,
                                           set(target.lpf_drop))

    missing = set(target.lpf_drop) - {d[0] for d in dropped}
    if missing:
        raise RuntimeError(
            "%s: lpf_drop names %s, which %s does not constrain.\n"
            "  Either a typo, or the board .lpf changed underneath this "
            "spec." % (target.name, ", ".join(sorted(missing)), base_rel))

    # The PMODs' own constraints.
    emitted = []
    for pm in target.pmods:
        balls = target.pmod_ports[pm.port]
        lines = ["", "# ---- %s in PMOD port %s (%s) ----"
                 % (pm.name, pm.port.upper(), pm.description)]
        for pin in sorted(pm.pins):
            port_name, ball = pm.pins[pin], balls[pin]
            lines.append('LOCATE COMP "%s" SITE "%s";\t# pin %d'
                         % (port_name, ball, pin))
            lines.append('IOBUF PORT "%s" IO_TYPE=%s;'
                         % (port_name, pm.io_type))
        unused = sorted(set(balls) - set(pm.pins))
        if unused:
            lines.append("#")
            lines.append("# Left UNCONSTRAINED on purpose -- this PMOD's "
                         "spec does not name them,")
            lines.append("# and some PMOD pins are outputs from the module "
                         "or pulled-up inputs")
            lines.append("# that must not be driven. See "
                         "release/hw/pmods/%s.spec." % pm.name)
            for u in unused:
                lines.append("#   pin %-2d  %s" % (u, balls[u]))
        emitted.append("\n".join(lines) + "\n")

    pieces = [(base_rel, base_text)]
    for pm, text in zip(target.pmods, emitted):
        pieces.append(("%s@%s" % (pm.name, pm.port), text))

    conflicts = check_site_conflicts(pieces)
    if conflicts:
        raise RuntimeError(
            "%s: two ports on the same ball.\n\n  %s\n\n"
            "  Place-and-route would reject this. Two PMODs sharing a "
            "port, or a PMOD pin colliding with something the board\n"
            "  constrains outside any port -- add it to lpf_drop if the "
            "PMOD should win."
            % (target.name, "\n  ".join(conflicts)))

    header = ["# GENERATED FILE -- DO NOT EDIT, DO NOT COMMIT.",
              "# %s, with PMOD ports rewired for target %s." % (target.lpf,
                                                                target.name),
              "# Written by release/zrelease; removed when the build ends.",
              "#"]
    for pm in target.pmods:
        header.append("#   port %s: %s" % (pm.port.upper(), pm.description))
    if dropped:
        header.append("#")
        header.append("# released from the base .lpf:")
        for name, why in dropped:
            header.append("#   %-12s %s" % (name, why))
    header.append("")

    body = []
    for label, text in pieces:
        body.append("")
        body.append("# ---- %s ----" % label if not label.count("@") else "")
        body.append(text.rstrip())
        body.append("")

    # Named with a marker prefix rather than just "<target>.lpf".
    # boards/ is full of hand-written, checked-in constraint files and
    # a generated one sitting among them looks exactly like another one
    # of those -- which matters most at the moment it should not be
    # there at all, i.e. after a build died before cleaning up.
    relpath = "boards/.zrelease-%s.lpf" % target.name
    return relpath, "\n".join(header) + "\n".join(body) + "\n"


def effective_pins(text):
    """{port name: ball} for the constraints still live in an .lpf."""
    return {port: site for port, site, _ in _locates(text)}


def check_lpf_equivalence(root, target):
    """Does the generated .lpf place every port where the board .lpf did?

    Only meaningful for a target whose PMODs restore what the board
    assumed -- lakritz_uart, where the usbuart spec puts UART0_TX and
    UART0_RX back on the same two balls the base .lpf had them on. If
    that comes out different, the PMOD pin map and the board port map
    disagree about something, and the resulting bitstream would drive
    the console pins somewhere unexpected.

    Differences are EXPECTED for a target that changes the hardware --
    lakritz_langkatze genuinely removes UART0 and adds five ETH ports.
    So this reports the difference rather than judging it, and the
    caller decides.

    Returns (added, removed, moved).
    """
    rel, text = merged_lpf(root, target)
    if rel is None:
        return [], [], []

    with open(os.path.join(root, "boards", target.lpf)) as f:
        base = effective_pins(f.read())
    now = effective_pins(text)

    added = sorted(set(now) - set(base))
    removed = sorted(set(base) - set(now))
    moved = sorted((p, base[p], now[p]) for p in set(base) & set(now)
                   if base[p] != now[p])
    return added, removed, moved


def check_port_coverage(root, target, spec_mod):
    """Every port rtl/sysctl.v declares must be constrained, and vice versa.

    nextpnr-ecp5 is run without --lpf-allow-unconstrained, so a declared
    port with no LOCATE is a hard failure -- and the PMOD system creates
    exactly that situation whenever it releases a base-.lpf constraint
    whose port is still built. nextpnr names the port; it does not know
    which define would have removed it, or that a PMOD took its pins.

    Bus ports are constrained per bit ("sdram_a[0]"), so the base name
    is what counts.

    The reverse direction -- a constraint for a port that no longer
    exists -- is only a warning. The board .lpf already has several
    (SD_DAT1, SD_DAT2), so it is clearly tolerated, and this tool is in
    no position to start rejecting the tree's existing files.
    """
    rel, text = merged_lpf(root, target)
    if rel is None:
        with open(os.path.join(root, "boards", target.lpf)) as f:
            text = f.read()

    constrained = {re.sub(r"\[.*", "", p) for p in effective_pins(text)}
    declared = spec_mod.declared_ports(root, target.defines)

    problems = []
    for guard, name in declared:
        if name in constrained:
            continue
        if guard:
            problems.append(
                "port '%s' is declared (rtl/sysctl.v, inside `ifdef %s) "
                "but nothing constrains it.\n"
                "    Either give it pins, or add '-%s' to the target spec "
                "so the port is not built." % (name, guard, guard))
        else:
            problems.append(
                "port '%s' is declared unconditionally in rtl/sysctl.v but "
                "nothing constrains it.\n"
                "    A PMOD has probably taken its ball. It has no `ifdef "
                "to remove, so it needs pins somewhere." % name)
    return problems
