/* Generated by sw/data/images/gen_logo_small.py -- do not hand-edit. */
/* Regenerate if zeitlos.bin changes. */

#ifndef LOGO_SMALL_H
#define LOGO_SMALL_H

#include <stdint.h>

/*
 * The Zeitlos logo, downscaled from the 512x384 original in
 * sw/data/images/zeitlos.bin.
 *
 * Stored in the FRAMEBUFFER's own bit order -- pixel x at bit (x & 31)
 * of word (x >> 5), least significant bit leftmost -- so it reaches
 * the screen through one z_fb_hw_blit_mem() call with no per-pixel
 * work at runtime. Pass Z_LOGO_SMALL_STRIDE as the source stride.
 */

#define Z_LOGO_SMALL_W       96
#define Z_LOGO_SMALL_H       18
#define Z_LOGO_SMALL_WORDS   3
#define Z_LOGO_SMALL_STRIDE  (Z_LOGO_SMALL_WORDS * 4)

extern const uint32_t z_logo_small[Z_LOGO_SMALL_H][Z_LOGO_SMALL_WORDS];

#endif
