#ifndef CS_BANNER_IMG_H
#define CS_BANNER_IMG_H

/*
 * Zeitlos Casino -- the banner.
 *
 * GENERATED by gen_banner.py. Do not edit; replace banner.png and
 * re-run it.
 *
 * One uint32_t per word with the LEAST significant bit leftmost, the
 * same packing the card and slot tiles use and what z_fb_hw_blit_mem()
 * expects -- the opposite of the font's MSB-first rows.
 *
 * Row r starts at cs_banner[r * CS_BANNER_STRIDE_W].
 */

#include <stdint.h>

#define CS_BANNER_W 312
#define CS_BANNER_H 88
#define CS_BANNER_STRIDE_W 10
#define CS_BANNER_STRIDE (10 * 4)   /* BYTES, as z_fb_hw_blit_mem takes it */

extern const uint32_t cs_banner[];

#endif
