#ifndef CHESS_PIECES_H
#define CHESS_PIECES_H

/*
 * Zeitlos chess -- board tiles.
 *
 * GENERATED by gen_pieces.py. Do not edit; edit the generator and run
 * it. See that file for why a square is a precomposed opaque tile
 * rather than a background plus a masked sprite.
 *
 * Each tile is 24x24, one uint32_t per row, so the source STRIDE IS 4
 * BYTES -- which is not padding, it is what the blitter requires. It
 * walks the source by adding the stride to a BYTE address while
 * issuing word reads that ignore the low two bits, so a 24-pixel-wide
 * tile stored three bytes to the row would make rows resolve to the
 * same word and repeat.
 *
 * Bit order is the framebuffer's: pixel x at bit (x & 31), least
 * significant bit LEFTMOST. That is the opposite of font and icon
 * data (zfont.h, zicon.h). Getting it backwards mirrors each tile
 * horizontally, which on a chessboard looks like the knights facing
 * the wrong way and nothing else -- worth knowing, because that is a
 * symptom people mistake for an art choice.
 */

#include <stdint.h>

#define CP_TILE_W 24
#define CP_TILE_H 24
#define CP_TILE_STRIDE 4

/* Background: which colour square the tile is composed against. */
#define CP_LIGHT 0
#define CP_DARK  1

/* Contents: 0 is an empty square, then white pawn..king, then black
 * pawn..king. cp_tile_index() converts a ce_core.c piece byte. */
#define CP_EMPTY 0

extern const uint32_t cp_tiles[2][13][CP_TILE_H];

#endif
