#!/usr/bin/env python3
# Zeitlos -- regenerates tests/p256_vectors.h.
#
#   python3 gen_p256_vectors.py > p256_vectors.h
#
# Signatures from python-cryptography, i.e. OpenSSL. Checked in rather
# than regenerated per build, so the suite needs no crypto library and
# a failure means the C changed rather than the key did.
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.primitives import hashes, serialization
import hashlib
def c(name,b):
    print("static const uint8_t %s[] = {"%name,end="")
    for i,x in enumerate(b):
        if i%12==0: print("\n\t",end="")
        print("0x%02x, "%x,end="")
    print("\n};")
print("/* GENERATED by tests/gen_p256_vectors.py -- do not hand edit. */")
for idx in range(4):
    k = ec.generate_private_key(ec.SECP256R1())
    pub = k.public_key().public_bytes(serialization.Encoding.X962,
            serialization.PublicFormat.UncompressedPoint)
    msg = b"p256 case %d" % idx
    sig = k.sign(msg, ec.ECDSA(hashes.SHA256()))
    r,s = utils.decode_dss_signature(sig)
    c("p%d_pub"%idx, pub); c("p%d_h"%idx, hashlib.sha256(msg).digest())
    c("p%d_r"%idx, r.to_bytes(32,'big')); c("p%d_s"%idx, s.to_bytes(32,'big'))
