#!/usr/bin/env python3
#
# Zeitlos
# Copyright (c) 2026 Lone Dynamics Corporation. All rights reserved.
#
# Regenerates tests/rsa_vectors.h.
#
#   python3 gen_rsa_vectors.py > rsa_vectors.h
#
# The signatures are made by python-cryptography, i.e. by OpenSSL --
# an implementation with nothing in common with the C being tested.
# There is no RFC vector for this the way there is for HMAC or HKDF,
# because a signature depends on a key; the equivalent of a published
# constant here is "something a widely deployed implementation
# produced and considers valid".
#
# The output is CHECKED IN rather than regenerated on every build, so
# the suite does not need python-cryptography to run and so a failure
# means the C changed rather than the key did. Rerun this only when
# adding cases.
#
# Key sizes are deliberately 2048 AND 3072. A single size hides
# bugs whose behaviour depends on where the modulus boundary falls --
# the PSS masked-bit handling was wrong in a way that passed at 2048
# and failed at 3072, purely because one mask bit happened to differ.

from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes
import hashlib

def c(name, b):
    print("static const uint8_t %s[] = {" % name, end="")
    for i, x in enumerate(b):
        if i % 12 == 0: print("\n\t", end="")
        print("0x%02x, " % x, end="")
    print("\n};")

print("/* GENERATED by tests/gen_rsa_vectors.py -- do not hand edit. */")
print("/* Signatures produced by python-cryptography (OpenSSL). */\n")

for bits in (2048, 3072):
    k = rsa.generate_private_key(public_exponent=65537, key_size=bits)
    pn = k.public_key().public_numbers()
    msg = b"tbsCertificate stand-in for %d" % bits
    h = hashlib.sha256(msg).digest()
    p = "k%d_" % bits
    c(p + "n", pn.n.to_bytes(bits // 8, 'big'))
    c(p + "e", pn.e.to_bytes(3, 'big'))
    c(p + "h", h)
    c(p + "sig15", k.sign(msg, padding.PKCS1v15(), hashes.SHA256()))
    c(p + "sigpss", k.sign(msg,
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=32),
        hashes.SHA256()))

# e = 3. Small exponents are where a PKCS#1 v1.5 verifier that PARSES
# the DigestInfo instead of comparing it becomes forgeable
# (Bleichenbacher, and its several rediscoveries). rsa.c compares a
# fully constructed expected encoding; this case is here so that
# stays true.
k3 = rsa.generate_private_key(public_exponent=3, key_size=2048)
pn = k3.public_key().public_numbers()
msg = b"e3 case"
c("e3_n", pn.n.to_bytes(256, 'big'))
c("e3_e", pn.e.to_bytes(1, 'big'))
c("e3_h", hashlib.sha256(msg).digest())
c("e3_sig15", k3.sign(msg, padding.PKCS1v15(), hashes.SHA256()))
