#!/usr/bin/env python3
# Zeitlos -- regenerates tests/solinas_vectors.h.
#
#   python3 gen_solinas_vectors.py > solinas_vectors.h
#
# Schoolbook products and their reductions mod p, for both curves.
# Corner cases first: (p-1)^2 and friends are where carry and borrow
# propagation goes wrong, and random values rarely reach them.
import random
random.seed(20260907)
P256 = 2**256 - 2**224 + 2**192 + 2**96 - 1
P384 = 2**384 - 2**128 - 2**96 + 2**32 - 1
def limbs(v, n): return [ (v >> (32*i)) & 0xFFFFFFFF for i in range(n) ]
def emit(name, vals):
    print("static const uint32_t %s[] = {" % name, end="")
    for i, w in enumerate(vals):
        if i % 6 == 0: print("\n\t", end="")
        print("0x%08X, " % w, end="")
    print("\n};")
print("/* GENERATED by tests/gen_solinas_vectors.py -- do not hand edit. */")
for tag, P, nl in (("p256", P256, 8), ("p384", P384, 12)):
    cases = [(P-1,P-1), (P-1,1), (1,1), (0,P-1), (2**(32*nl)-1-P, P-1)]
    cases += [(random.randrange(P), random.randrange(P)) for _ in range(25)]
    prods, reds = [], []
    for a, b in cases:
        prods += limbs(a*b, 2*nl); reds += limbs((a*b) % P, nl)
    emit(tag + "_prod", prods); emit(tag + "_red", reds)
    print("#define %s_CASES %d" % (tag.upper(), len(cases)))
