#!/usr/bin/env python3
# Regenerates ecdsa_many.h for test_ecdsa.c: signatures made by the
# `cryptography` package, which shares nothing with ecdsa.c.
#
#   python3 gen_ecdsa_many.py > ecdsa_many.h
#
# Per curve: 60 valid signatures (random keys and messages); each also
# tampered two ways -- a hash bit flipped (must fail) and s replaced by
# n - s (still valid for ECDSA: must pass, which catches a negation gone
# wrong). And the edge keys 1 (Q = G) and n - 1 (Q = -G, so G + Q is the
# point at infinity: the register-file path must give up and the classic
# one answer).
import random, hashlib
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature, Prehashed
from cryptography.hazmat.primitives import hashes, serialization
random.seed(20260927)
curves = [("EC_CURVE_P256", ec.SECP256R1(), hashes.SHA256(), hashlib.sha256, 32,
           0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551),
          ("EC_CURVE_P384", ec.SECP384R1(), hashes.SHA384(), hashlib.sha384, 48,
           int("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973", 16))]
rows = []
def c(b): return "{" + ",".join("0x%02x" % x for x in b) + "}"
for cid, curve, halg, hfn, nb, n in curves:
    keys = [random.randrange(1, n) for _ in range(60)] + [1, n - 1, 2, n - 2]
    for d in keys:
        k = ec.derive_private_key(d, curve)
        pub = k.public_key().public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
        msg = bytes(random.randrange(256) for _ in range(random.randrange(1, 100)))
        h = hfn(msg).digest()
        r, s = decode_dss_signature(k.sign(h, ec.ECDSA(Prehashed(halg))))
        rb, sb = r.to_bytes(nb, "big"), s.to_bytes(nb, "big")
        rows.append((cid, pub, rb, sb, h, 1))
        hb = bytearray(h); hb[random.randrange(len(hb))] ^= 1 << random.randrange(8)
        rows.append((cid, pub, rb, sb, bytes(hb), 0))
        rows.append((cid, pub, rb, (n - s).to_bytes(nb, "big"), h, 1))
print("// generated by gen_ecdsa_many.py -- do not edit")
print("typedef struct { ec_curve_id_t c; uint8_t pub[97]; uint8_t r[48], s[48], h[48]; uint8_t nb, ok; } many_t;")
print("static const many_t many[] = {")
for cid, pub, rb, sb, h, ok in rows:
    print("  {%s,%s,%s,%s,%s,%d,%d}," % (cid, c(pub), c(rb), c(sb), c(h), len(rb), ok))
print("};")
