#!/usr/bin/env python3
#
# Zeitlos
# Copyright (c) 2026 Lone Dynamics Corporation. All rights reserved.
#
# Regenerates tests/vectors.h, the expected answers for
# tests/test_tls_crypto.c.
#
#   python3 gen_vectors.py > vectors.h
#
# WHY THIS EXISTS RATHER THAN HAND-TYPED CONSTANTS
#
# Every value here is computed by Python's hashlib/hmac and the
# `cryptography` package -- implementations with nothing in common
# with the C being tested. Hand-transcribing them out of the RFCs
# instead would test the C against my typing.
#
# The generator itself is checked against PUBLISHED values, so a bug
# in it cannot quietly become the expected answer. Eight of the
# outputs below are documented constants and are verified at the
# bottom of this script:
#
#   RFC 4231   HMAC-SHA256 test cases 2 and 6
#   RFC 5869   HKDF-SHA256 test cases 1 and 3
#   RFC 8439   AEAD_CHACHA20_POLY1305, section 2.8.2
#   RFC 8446   the no-PSK early secret and its "derived" successor,
#              which are fixed constants for every TLS 1.3 connection
#
# The remaining values -- the full key schedule -- use a synthetic
# ECDHE output and stand-in transcript hashes. They are not from any
# RFC; they exist so that a change to the schedule shows up as a
# failure rather than as a handshake that mysteriously stops working.
#
# Needs Pillow-free stdlib plus `cryptography`.

import hashlib, hmac, sys
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305

def H(b): return hashlib.sha256(b).digest()
def hm(k, d): return hmac.new(k, d, hashlib.sha256).digest()

def hkdf_extract(salt, ikm):
    if not salt: salt = b"\x00" * 32
    return hm(salt, ikm)

def hkdf_expand(prk, info, n):
    out = b""; t = b""; i = 1
    while len(out) < n:
        t = hm(prk, t + info + bytes([i])); out += t; i += 1
    return out[:n]

def expand_label(secret, label, ctx, n):
    full = b"tls13 " + label
    info = n.to_bytes(2, 'big') + bytes([len(full)]) + full \
        + bytes([len(ctx)]) + ctx
    return hkdf_expand(secret, info, n)

def derive_secret(secret, label, msgs_hash):
    return expand_label(secret, label, msgs_hash, 32)

VALUES = {}

def c(name, b):
    VALUES[name] = b
    print("static const uint8_t %s[] = {" % name, end="")
    for i, x in enumerate(b):
        if i % 12 == 0: print("\n\t", end="")
        print("0x%02x, " % x, end="")
    print("\n};")

print("/* GENERATED by tests/gen_vectors.py -- do not hand edit. */")
print("/* Expected values computed with Python's hashlib/hmac and the")
print("   `cryptography` package: implementations entirely independent")
print("   of the C under test, which is the point. */\n")

# -- RFC 4231, HMAC-SHA256 --
k = b"Jefe"; d = b"what do ya want for nothing?"
c("hmac_key_2", k); c("hmac_data_2", d); c("hmac_want_2", hm(k, d))

k4 = bytes(range(1, 26)); d4 = b"\xcd" * 50
c("hmac_key_4", k4); c("hmac_data_4", d4); c("hmac_want_4", hm(k4, d4))

# A key longer than the 64-byte block, which must be hashed first.
k6 = b"\xaa" * 131
d6 = b"Test Using Larger Than Block-Size Key - Hash Key First"
c("hmac_key_6", k6); c("hmac_data_6", d6); c("hmac_want_6", hm(k6, d6))

# -- RFC 5869, HKDF-SHA256 --
ikm = b"\x0b" * 22; salt = bytes(range(0x00, 0x0d))
info = bytes(range(0xf0, 0xfa))
prk = hkdf_extract(salt, ikm)
c("hkdf1_ikm", ikm); c("hkdf1_salt", salt); c("hkdf1_info", info)
c("hkdf1_prk", prk); c("hkdf1_okm", hkdf_expand(prk, info, 42))

# Zero-length salt and info -- the case where "empty" must become 32
# zero bytes rather than being skipped.
ikm3 = b"\x0b" * 22
prk3 = hkdf_extract(b"", ikm3)
c("hkdf3_ikm", ikm3); c("hkdf3_prk", prk3)
c("hkdf3_okm", hkdf_expand(prk3, b"", 42))

# -- RFC 8439 section 2.8.2, AEAD_CHACHA20_POLY1305 --
key = bytes(range(0x80, 0xa0))
nonce = bytes.fromhex("070000004041424344454647")
aad = bytes.fromhex("50515253c0c1c2c3c4c5c6c7")
pt = (b"Ladies and Gentlemen of the class of '99: If I could offer you "
      b"only one tip for the future, sunscreen would be it.")
ct = ChaCha20Poly1305(key).encrypt(nonce, pt, aad)
c("aead_key", key); c("aead_nonce", nonce); c("aead_aad", aad)
c("aead_pt", pt); c("aead_ct", ct[:-16]); c("aead_tag", ct[-16:])

# -- the TLS 1.3 key schedule, end to end --
early = hkdf_extract(None, b"\x00" * 32)
c("ks_early", early)
c("ks_derived_early", derive_secret(early, b"derived", H(b"")))

ecdhe = bytes(range(32))
hs = hkdf_extract(derive_secret(early, b"derived", H(b"")), ecdhe)
c("ks_ecdhe", ecdhe); c("ks_handshake", hs)

th_sh = H(b"ClientHello||ServerHello")
c("ks_th_sh", th_sh)
chs = derive_secret(hs, b"c hs traffic", th_sh)
shs = derive_secret(hs, b"s hs traffic", th_sh)
c("ks_client_hs", chs); c("ks_server_hs", shs)
c("ks_chs_key", expand_label(chs, b"key", b"", 32))
c("ks_chs_iv", expand_label(chs, b"iv", b"", 12))

master = hkdf_extract(derive_secret(hs, b"derived", H(b"")), b"\x00" * 32)
c("ks_master", master)

th_sf = H(b"...ServerFinished")
c("ks_th_sf", th_sf)
c("ks_client_ap", derive_secret(master, b"c ap traffic", th_sf))
c("ks_server_ap", derive_secret(master, b"s ap traffic", th_sf))

th_fin = H(b"transcript up to Finished")
fk = expand_label(shs, b"finished", b"", 32)
c("ks_th_fin", th_fin); c("ks_finished", hm(fk, th_fin))

c("ks_updated", expand_label(chs, b"traffic upd", b"", 32))

# -- record nonce: iv XOR seq, right-aligned, big-endian --
iv = bytes.fromhex("0102030405060708090a0b0c")
c("nonce_iv", iv)
for seq in (0, 1, 0x1234, 0x0102030405060708):
    n = bytearray(iv)
    for i in range(8):
        n[11 - i] ^= (seq >> (8 * i)) & 0xff
    c("nonce_seq_%x" % seq, bytes(n))

# -- self-check against published values --
#
# If this generator is wrong, its output becomes the "expected"
# answer and the C test passes while agreeing with a bug. These eight
# are documented constants; a mismatch stops the build.
PUBLISHED = {
    'hmac_want_2': '5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843',
    'hmac_want_6': '60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54',
    'hkdf1_prk':   '077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5',
    'hkdf1_okm':   '3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf34007208d5b887185865',
    'hkdf3_prk':   '19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04',
    'ks_early':    '33ad0a1c607ec03b09e6cd9893680ce210adf300aa1f2660e1b22e10f170f92a',
    'ks_derived_early': '6f2615a108c702c5678f54fc9dbab69716c076189c48250cebeac3576c3611ba',
    'aead_tag':    '1ae10b594f09e26a7e902ecbd0600691',
}

bad = [k for k, v in PUBLISHED.items() if VALUES[k].hex() != v]
if bad:
    sys.stderr.write("gen_vectors.py: DISAGREES WITH PUBLISHED VALUES: %s\n"
                     % ", ".join(bad))
    sys.exit(1)

sys.stderr.write("gen_vectors.py: %d values, %d cross-checked against "
                 "published constants\n" % (len(VALUES), len(PUBLISHED)))
