#!/usr/bin/env python3
# Zeitlos -- regenerates tests/ecdsa_vectors.h.
#
#   python3 gen_ecdsa_vectors.py > ecdsa_vectors.h
#
# Signatures from python-cryptography (OpenSSL). Every combination of
# curve and hash size is generated, because SEC1 truncates a hash
# longer than the curve order and uses a shorter one whole -- and both
# occur on real certificate chains.
from cryptography.hazmat.primitives.asymmetric import ec, utils
from cryptography.hazmat.primitives import hashes, serialization
import hashlib
def c(n,b):
    print("static const uint8_t %s[] = {"%n,end="")
    for i,x in enumerate(b):
        if i%12==0: print("\n\t",end="")
        print("0x%02x, "%x,end="")
    print("\n};")
print("/* GENERATED by tests/gen_ecdsa_vectors.py -- do not hand edit. */")
cases=[("p256",ec.SECP256R1(),hashes.SHA256(),"sha256"),
       ("p384",ec.SECP384R1(),hashes.SHA384(),"sha384"),
       ("p384x",ec.SECP384R1(),hashes.SHA256(),"sha256"),
       ("p256x",ec.SECP256R1(),hashes.SHA384(),"sha384")]
for name,curve,h,hn in cases:
    k=ec.generate_private_key(curve)
    pub=k.public_key().public_bytes(serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint)
    msg=b"case "+name.encode()
    r,s=utils.decode_dss_signature(k.sign(msg,ec.ECDSA(h)))
    nb = 48 if curve.name=="secp384r1" else 32
    d = hashlib.sha256(msg).digest() if hn=="sha256" else hashlib.sha384(msg).digest()
    c(name+"_pub",pub); c(name+"_h",d)
    c(name+"_r",r.to_bytes(nb,'big')); c(name+"_s",s.to_bytes(nb,'big'))
