/*
 * Zeitlos
 * Copyright (c) 2026 Lone Dynamics Corporation. All rights reserved.
 *
 * Host tests for verify.c: chain validation against real certificates
 * that OpenSSL issued (tests/gen_chain.sh, corpus in tests/chain/).
 *
 * The positive cases prove the arithmetic and the parsing hold
 * together. THE NEGATIVE CASES ARE THE POINT. A chain validator that
 * accepts every good chain and also accepts some bad ones passes
 * every test anyone writes by accident, and the bad ones it accepts
 * are precisely what an attacker supplies.
 *
 * So each rejection below corresponds to a real, named attack:
 *
 *   wrong hostname          a valid certificate for another domain
 *   self-signed root sent   the simplest possible forged chain
 *   unknown root            a chain anchored to nothing local
 *   non-CA as issuer        the single most damaging X.509 bug --
 *                           any leaf certificate minting others
 *   tampered tbsCertificate a modified name with the old signature
 *   expired                 a certificate whose key is now suspect
 *   no clock                refusing rather than skipping the check
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../verify.h"

static int fails, checks;

static void ck(int cond, const char *what) {
	checks++;
	if (!cond) { fails++; printf("FAIL: %s\n", what); }
}

// A rejection must be a rejection FOR A REASON. A validator that
// returns false with no message is one whose failures cannot be told
// apart from bugs.
//
// Written as a macro that calls verify_chain ITSELF, rather than a
// function taking (result, err). The function version reads `err` as
// an argument, and C does not specify the order arguments are
// evaluated in -- so it was read before the call that sets it, and
// every rejection looked like it had no reason attached.
static void ck_reject(bool ok, const char **errp, const char *what) {
	checks++;
	if (ok) { fails++; printf("FAIL: %s -- ACCEPTED\n", what); return; }
	checks++;
	if (!*errp) {
		fails++;
		printf("FAIL: %s -- rejected with no reason\n", what);
	}
}

typedef struct { uint8_t d[4096]; uint32_t n; } blob_t;

static blob_t load(const char *name) {
	blob_t b;
	char path[256];
	FILE *f;
	snprintf(path, sizeof(path), "tests/chain/%s.der", name);
	f = fopen(path, "rb");
	if (!f) { fprintf(stderr, "cannot open %s\n", path); exit(2); }
	b.n = (uint32_t)fread(b.d, 1, sizeof(b.d), f);
	fclose(f);
	return b;
}

// -- the root store, as an in-memory array --

static blob_t roots[4];
static int nroots;

static bool find_root(void *user, const der_t *issuer, x509_cert_t *out) {
	(void)user;
	for (int i = 0; i < nroots; i++) {
		const char *e = NULL;
		if (!x509_parse(roots[i].d, roots[i].n, out, &e)) continue;
		if (out->subject.len == issuer->len &&
			!memcmp(out->subject.p, issuer->p, issuer->len))
			return true;
	}
	return false;
}

static bool no_roots(void *user, const der_t *issuer, x509_cert_t *out) {
	(void)user; (void)issuer; (void)out;
	return false;
}

// A time inside the long-lived certificates' window and outside the
// deliberately short-lived one.
//
// Derived from the corpus rather than hard-coded: the certificates
// are generated by tests/gen_chain.sh whenever someone runs it, so a
// fixed timestamp would make this suite start failing on a date
// nobody chose.
static int64_t NOW;

static void pick_now(const blob_t *leaf) {
	x509_cert_t c;
	const char *e = NULL;
	if (!x509_parse(leaf->d, leaf->n, &c, &e)) {
		fprintf(stderr, "cannot parse the corpus: %s\n", e ? e : "?");
		exit(2);
	}
	// Thirty days after issue: inside the 3650-day certificates and
	// well past the one-day one.
	NOW = c.not_before + 30LL * 86400;
}

int main(void) {

	blob_t leafr = load("leafr"), interr = load("interr"), rootr = load("rootr");
	blob_t leafe = load("leafe"), roote = load("roote");
	blob_t notca = load("notca"), under = load("under"), expd = load("exp");
	const char *err;
	cert_blob_t ch[VERIFY_MAX_CHAIN];

	pick_now(&leafr);

	roots[0].n = rootr.n; memcpy(roots[0].d, rootr.d, rootr.n);
	roots[1].n = roote.n; memcpy(roots[1].d, roote.d, roote.n);
	nroots = 2;

	// -- valid: RSA leaf, RSA intermediate, RSA root --
	ch[0].der = leafr.d; ch[0].len = leafr.n;
	ch[1].der = interr.d; ch[1].len = interr.n;
	err = NULL;
	ck(verify_chain(ch, 2, "example.test", NOW, find_root, NULL, &err),
		"RSA chain verifies");
	if (err) printf("  (reason given: %s)\n", err);

	// The wildcard SAN on the same leaf.
	ck(verify_chain(ch, 2, "www.example.test", NOW, find_root, NULL, &err),
		"wildcard SAN matches one label");

	// -- valid: ECDSA leaf directly under an ECDSA root --
	ch[0].der = leafe.d; ch[0].len = leafe.n;
	ck(verify_chain(ch, 1, "ec.example.test", NOW, find_root, NULL, &err),
		"ECDSA chain verifies");

	// -- a certificate for someone else --
	ch[0].der = leafr.d; ch[0].len = leafr.n;
	ch[1].der = interr.d; ch[1].len = interr.n;
	err = NULL;
	ck_reject(verify_chain(ch, 2, "attacker.test", NOW, find_root, NULL, &err),
		&err, "rejects a certificate for a different host");

	// A wildcard must not match more than one label, and must not
	// match the bare domain.
	err = NULL;
	ck_reject(verify_chain(ch, 2, "a.b.example.test", NOW, find_root, NULL, &err),
		&err, "wildcard does not match two labels");

	// -- a chain anchored to nothing we trust --
	err = NULL;
	ck_reject(verify_chain(ch, 2, "example.test", NOW, no_roots, NULL, &err),
		&err, "rejects a chain with no known root");

	// -- the server sends its own root, self-signed --
	//
	// The simplest forged chain there is: anyone can make one.
	ch[0].der = leafr.d; ch[0].len = leafr.n;
	ch[1].der = interr.d; ch[1].len = interr.n;
	ch[2].der = rootr.d; ch[2].len = rootr.n;
	err = NULL;
	ck_reject(verify_chain(ch, 3, "example.test", NOW, no_roots, NULL, &err),
		&err, "a self-signed root from the server is not trusted");

	// -- a non-CA certificate used as an issuer --
	//
	// If this is accepted, anyone holding any valid certificate can
	// issue certificates for every domain on the internet.
	ch[0].der = under.d; ch[0].len = under.n;
	ch[1].der = notca.d; ch[1].len = notca.n;
	err = NULL;
	ck_reject(verify_chain(ch, 2, "under.test", NOW, find_root, NULL, &err),
		&err, "rejects a non-CA certificate used as an issuer");

	// -- a modified certificate with its original signature --
	{
		static blob_t t;
		t = leafr;
		// Flip a byte inside the tbsCertificate. The signature is
		// untouched, so this is exactly a forged field.
		t.d[60] ^= 0x01;
		ch[0].der = t.d; ch[0].len = t.n;
		ch[1].der = interr.d; ch[1].len = interr.n;
		err = NULL;
		ck_reject(verify_chain(ch, 2, "example.test", NOW, find_root, NULL, &err),
			&err, "rejects a tampered certificate");
	}

	// -- dates --
	ch[0].der = expd.d; ch[0].len = expd.n;
	ch[1].der = interr.d; ch[1].len = interr.n;
	err = NULL;
	ck_reject(verify_chain(ch, 2, "old.test", NOW, find_root, NULL, &err),
		&err, "rejects an expired certificate");

	// No clock is a refusal, not a licence to skip the check.
	ch[0].der = leafr.d; ch[0].len = leafr.n;
	err = NULL;
	ck_reject(verify_chain(ch, 2, "example.test", 0, find_root, NULL, &err),
		&err, "refuses to validate without a clock");

	// -- structural --
	err = NULL;
	ck_reject(verify_chain(ch, 0, "example.test", NOW, find_root, NULL, &err),
		&err, "rejects an empty chain");

	// Chain in the wrong order.
	ch[0].der = interr.d; ch[0].len = interr.n;
	ch[1].der = leafr.d; ch[1].len = leafr.n;
	err = NULL;
	ck_reject(verify_chain(ch, 2, "example.test", NOW, find_root, NULL, &err),
		&err, "rejects a chain in the wrong order");

	// Garbage.
	{
		static uint8_t junk[64];
		memset(junk, 0xA5, sizeof(junk));
		ch[0].der = junk; ch[0].len = sizeof(junk);
		err = NULL;
		ck_reject(verify_chain(ch, 1, "example.test", NOW, find_root, NULL, &err),
			&err, "rejects garbage");
	}

	// -- the shape that actually broke on the real web --
	//
	// A P-384 ECDSA intermediate signing a P-256 leaf with SHA-384,
	// under a P-384 root. That is the DigiCert "Hybrid ECC SHA384"
	// arrangement, and en.wikipedia.org's version of it is what
	// produced "EC key is not P-256" from the parser. Before P-384
	// and SHA-384 existed here, every certificate below parsed
	// perfectly and the one signature that mattered could not be
	// checked at all.
	{
		blob_t l384 = load("leaf384"), i384 = load("int384");
		blob_t r384 = load("root384");

		roots[2].n = r384.n;
		memcpy(roots[2].d, r384.d, r384.n);
		nroots = 3;

		ch[0].der = l384.d; ch[0].len = l384.n;
		ch[1].der = i384.d; ch[1].len = i384.n;
		err = NULL;
		ck(verify_chain(ch, 2, "ecc.example.test", NOW, find_root, NULL, &err),
			"P-384 intermediate over a P-256 leaf, SHA-384 throughout");
		if (err) printf("  (reason given: %s)\n", err);

		err = NULL;
		ck_reject(verify_chain(ch, 2, "attacker.test", NOW, find_root,
			NULL, &err), &err,
			"P-384 chain still rejects the wrong host");

		// And a tampered one, so the SHA-384 path is shown to be
		// checking rather than merely running.
		{
			static blob_t t;
			t = l384;
			t.d[60] ^= 0x01;
			ch[0].der = t.d; ch[0].len = t.n;
			err = NULL;
			ck_reject(verify_chain(ch, 2, "ecc.example.test", NOW,
				find_root, NULL, &err), &err,
				"P-384 chain rejects a tampered certificate");
		}
	}

	// RSA signed with SHA-384: the other half of the same gap.
	{
		blob_t l = load("leaf384r"), r = load("root384r");

		roots[3].n = r.n;
		memcpy(roots[3].d, r.d, r.n);
		nroots = 4;

		ch[0].der = l.d; ch[0].len = l.n;
		err = NULL;
		ck(verify_chain(ch, 1, "rsa384.example.test", NOW, find_root,
			NULL, &err), "RSA chain signed with SHA-384");
		if (err) printf("  (reason given: %s)\n", err);
	}

	// -- the verification cache must not become a bypass --
	//
	// It is keyed on the host and on every byte of the chain, and it
	// expires with the certificates. Each of those is a way the cache
	// could otherwise turn a rejection into an acceptance, which is
	// the only kind of caching bug that matters.
	{
		blob_t l = load("leafr"), i2 = load("interr");

		ch[0].der = l.d; ch[0].len = l.n;
		ch[1].der = i2.d; ch[1].len = i2.n;

		// Prime it.
		err = NULL;
		ck(verify_chain(ch, 2, "example.test", NOW, find_root, NULL, &err),
			"cache: first verification succeeds");

		// A hit must be a hit.
		err = NULL;
		ck(verify_chain(ch, 2, "example.test", NOW, find_root, NULL, &err),
			"cache: repeat verification succeeds");

		// A DIFFERENT host with the same chain must not be served the
		// cached answer.
		err = NULL;
		ck_reject(verify_chain(ch, 2, "attacker.test", NOW, find_root,
			NULL, &err), &err, "cache: does not cross hosts");

		// Nor may an expired cache entry be used.
		err = NULL;
		ck_reject(verify_chain(ch, 2, "example.test",
			NOW + 40LL * 365 * 86400, find_root, NULL, &err), &err,
			"cache: expires with the chain");

		// Nor a chain that differs by one byte.
		{
			static blob_t t;
			t = l;
			t.d[60] ^= 0x01;
			ch[0].der = t.d; ch[0].len = t.n;
			err = NULL;
			ck_reject(verify_chain(ch, 2, "example.test", NOW, find_root,
				NULL, &err), &err, "cache: a changed byte misses");
		}

		// And with no clock the cache must not stand in for the date
		// check it cannot perform.
		ch[0].der = l.d; ch[0].len = l.n;
		err = NULL;
		ck_reject(verify_chain(ch, 2, "example.test", 0, find_root,
			NULL, &err), &err, "cache: still refuses without a clock");
	}

	// -- anchoring early must not skip a check --
	//
	// The walk stops at the first certificate whose issuer the local
	// store recognises, which saves signature verifications. The
	// thing to prove is that it saves only WORK, never a check: a bad
	// signature below the anchor, or a non-CA below it, must still be
	// caught.
	{
		blob_t l = load("leafr"), i2 = load("interr"), r = load("rootr");

		roots[0].n = r.n; memcpy(roots[0].d, r.d, r.n);
		nroots = 1;

		// A chain with EXTRA certificates after the anchor. The
		// intermediate is issued by a root we hold, so everything
		// beyond it is irrelevant -- but the leaf's own signature
		// must still be verified.
		ch[0].der = l.d;  ch[0].len = l.n;
		ch[1].der = i2.d; ch[1].len = i2.n;
		ch[2].der = r.d;  ch[2].len = r.n;     // server-supplied root
		err = NULL;
		ck(verify_chain(ch, 3, "example.test", NOW, find_root, NULL, &err),
			"anchors early and ignores the trailing certificate");

		// Now break the LEAF, below the anchor point. Anchoring must
		// not let it through.
		{
			static blob_t t;
			t = l;
			t.d[60] ^= 0x01;
			ch[0].der = t.d; ch[0].len = t.n;
			err = NULL;
			ck_reject(verify_chain(ch, 3, "example.test", NOW, find_root,
				NULL, &err), &err,
				"a tampered leaf is still caught below the anchor");
		}

		nroots = 4;   // restore for anything after
	}

	printf("%s: %d checks, %d failures\n",
		fails ? "FAIL" : "ok", checks, fails);

	return fails ? 1 : 0;

}
