/* Generated by gen_cards.py -- do not hand-edit. */
/* Re-run that script after changing the art; the output is committed
 * so the build needs no Python. */

#ifndef PK_CARDS_ART_H
#define PK_CARDS_ART_H

#include <stdint.h>

/*
 * Card tiles, 1bpp, one uint32_t per row with the LEAST significant
 * bit leftmost -- the source format z_fb_hw_blit_mem() reads, which is
 * the opposite of the MSB-first order z_font_t and zicon.h use. A tile
 * is therefore 4 bytes of stride regardless of its width.
 *
 * Each tile is OPAQUE: white body, black border, and it replaces
 * whatever was underneath. See gen_cards.py for why that matters and
 * why there are two sizes.
 *
 * Index by the card byte from pk_cards.h, 0..51. Row r of card c is
 * pk_card_full[c * PK_ART_FULL_H + r].
 */

#define PK_ART_FULL_W 20
#define PK_ART_FULL_H 28
#define PK_ART_MINI_W 12
#define PK_ART_MINI_H 17
#define PK_ART_STRIDE 4

/* How far apart overlapped mini cards are drawn. The rank and the suit
 * letter both live in columns 2..6, so at this stride every card in a
 * fan still shows both, with a column of white to spare. Seven cards
 * -- a full seven-card stud hand -- occupy 60 pixels, which is what a
 * six-handed table has to spare per seat. */
#define PK_ART_MINI_STRIDE 8

extern const uint32_t pk_card_full[52 * PK_ART_FULL_H];
extern const uint32_t pk_card_mini[52 * PK_ART_MINI_H];
extern const uint32_t pk_back_full[PK_ART_FULL_H];
extern const uint32_t pk_back_mini[PK_ART_MINI_H];

#endif
