#!/usr/bin/env python3
"""
Generates sw/common/zfont_data.c from the .mem bitmap sources in this
directory (sw/data/font/). See sw/common/zfont.h for the target format
this produces (z_font_t: w, h, first/last codepoint, glyph bytes).

A .mem source is named font<W>x<H>.mem (e.g. font6x12.mem) and is a
plain text grid: 96 glyphs (covering ASCII 0x20-0x7f, in order), each
`h` lines of `w` space-separated 0/1 values, one line per pixel row,
top row first. This is the same format sw/data/font/font16.mem
already used -- nothing new, just documented and given a real
generator, since gen_font_data.py was referenced in zfont.h's own
comment but wasn't actually checked into the repo.

Adding a new font: drop a new font<W>x<H>.mem here (W <= 8 -- see
zfont.h's own note on why: one byte per row, top W bits used, and
nothing else in this codebase currently supports wider glyphs), run
this script, and it'll show up as z_font_<W>x<H> in zfont_data.c,
declared in zfont.h alongside the others.

Usage:
    python3 gen_font_data.py
"""

import re
import sys
from pathlib import Path

FONT_DIR = Path(__file__).parent
OUT_FILE = FONT_DIR.parent.parent / "common" / "zfont_data.c"

FIRST_CODEPOINT = 0x20
LAST_CODEPOINT = 0x7f
NUM_GLYPHS = LAST_CODEPOINT - FIRST_CODEPOINT + 1  # 96


def parse_mem(path, w, h):
	rows = []
	with open(path) as f:
		for line in f:
			line = line.strip()
			if not line:
				continue
			bits = [int(x) for x in line.split()]
			if len(bits) != w:
				sys.exit(f"{path}: expected {w} values per row, got "
					f"{len(bits)}: {line!r}")
			rows.append(bits)

	expected_rows = NUM_GLYPHS * h
	if len(rows) != expected_rows:
		sys.exit(f"{path}: expected {expected_rows} rows ({NUM_GLYPHS} "
			f"glyphs x {h} rows), got {len(rows)}")

	# each row's `w` bits become the top `w` bits of one byte
	glyph_bytes = []
	for bits in rows:
		byte = 0
		for i, bit in enumerate(bits):
			if bit:
				byte |= (0x80 >> i)
		glyph_bytes.append(byte)

	return glyph_bytes


def codepoint_char(cp):
	# for the trailing comment on each glyph line -- printable as-is,
	# except ones that are awkward or actively wrong to print
	# literally: DEL isn't printable at all, and a trailing backslash
	# on a `//` comment line is a C line-continuation (silently
	# swallows the next line into the comment) -- gcc warns about
	# exactly this ([-Wcomment]), so spell it out instead.
	if cp == 0x20:
		return "space"
	if cp == 0x7f:
		return "?"  # DEL, not actually present in most of these fonts
	if cp == 0x5c:
		return "backslash"
	return chr(cp)


def emit_font(name, w, h, glyph_bytes, out):
	out.write(f"static const uint8_t z_font_{name}_data[{NUM_GLYPHS} * {h}] = {{\n")
	for g in range(NUM_GLYPHS):
		cp = FIRST_CODEPOINT + g
		row_bytes = glyph_bytes[g * h:(g + 1) * h]
		hex_str = ", ".join(f"0x{b:02x}" for b in row_bytes)
		out.write(f"\t{hex_str}, // 0x{cp:02x} {codepoint_char(cp)}\n")
	out.write("};\n\n")
	out.write(f"const z_font_t z_font_{name} = "
		f"{{ {w}, {h}, 0x{FIRST_CODEPOINT:02x}, 0x{LAST_CODEPOINT:02x}, "
		f"z_font_{name}_data }};\n\n")


def main():
	mem_files = sorted(FONT_DIR.glob("font*.mem"))
	if not mem_files:
		sys.exit(f"no font*.mem files found in {FONT_DIR}")

	fonts = []
	for path in mem_files:
		m = re.match(r"font(\d+)x(\d+)\.mem$", path.name)
		if not m:
			print(f"skipping {path.name} (doesn't match font<W>x<H>.mem)", file=sys.stderr)
			continue
		w, h = int(m.group(1)), int(m.group(2))
		if w > 8:
			sys.exit(f"{path.name}: width {w} > 8 not supported -- see "
				"this script's own header comment")
		glyph_bytes = parse_mem(path, w, h)
		fonts.append((f"{w}x{h}", w, h, glyph_bytes))
		print(f"parsed {path.name}: {w}x{h}, {len(glyph_bytes)} glyph bytes")

	with open(OUT_FILE, "w") as out:
		out.write("/* Generated by sw/data/font/gen_font_data.py -- do not hand-edit. */\n")
		out.write("/* Regenerate if a .mem source in sw/data/font/ changes. */\n\n")
		out.write("#include <stdint.h>\n")
		out.write('#include "zfont.h"\n\n')
		for name, w, h, glyph_bytes in fonts:
			emit_font(name, w, h, glyph_bytes, out)

	print(f"wrote {OUT_FILE}")


if __name__ == "__main__":
	main()
