#ifndef SL_ART_TILES_H
#define SL_ART_TILES_H

/*
 * Zeitlos slots -- symbol tiles.
 *
 * GENERATED by gen_slots.py. Do not edit; edit the generator and
 * re-run it. The output is committed, so it must regenerate
 * identically.
 *
 * One uint32_t per row with the LEAST significant bit leftmost, the
 * same packing the card art uses and what z_fb_hw_blit_mem() expects
 * -- the opposite of the font's MSB-first rows. A 32-wide tile is
 * exactly one word, so the stride is 1.
 *
 * Row r of symbol s is sl_sym_tile[s * SL_ART_H + r].
 *
 * The include guard is SL_ART_TILES_H, not SL_ART_H: the obvious guard
 * name collides with the tile-height macro two lines below it, which
 * the compiler reports as a redefinition and which would leave the
 * guard testing a number rather than its own presence.
 */

#include <stdint.h>

#define SL_ART_W 32
#define SL_ART_H 32
#define SL_ART_STRIDE 4      /* BYTES per row, as z_fb_hw_blit_mem takes it */

extern const uint32_t sl_sym_tile[];

#endif
