/* GENERATED by gen_sprites.py -- do not edit.
 * Edit the art in that script and re-run it instead.
 * See its header for the two formats and why they differ. */

#ifndef GAMEDEMO_SPRITES_H
#define GAMEDEMO_SPRITES_H

#include <stdint.h>

#define GD_TILE_W 16
#define GD_TILE_H 16
#define GD_SPR_W 16
#define GD_SPR_H 16

/* Tile ids -- index into gd_tiles[]. Order matters: the
 * level map stores these values directly, and GD_TILE_SOLID
 * below assumes every solid tile sorts at or after BOX. */
enum {
	GD_TILE_EMPTY = 0,
	GD_TILE_GROUND = 1,
	GD_TILE_GRASS = 2,
	GD_TILE_BOX = 3,
	GD_TILE_CHEESE = 4,
	GD_TILE_COUNT = 5
};

/* Each tile is GD_TILE_H rows of GD_TILE_W bits, LSB =
 * leftmost pixel -- the framebuffer's own bit order (zgfx.h),
 * NOT z_font_t's MSB-first one. */
extern const uint32_t gd_tile_empty[GD_TILE_H];
extern const uint32_t gd_tile_ground[GD_TILE_H];
extern const uint32_t gd_tile_grass[GD_TILE_H];
extern const uint32_t gd_tile_box[GD_TILE_H];
extern const uint32_t gd_tile_cheese[GD_TILE_H];

extern const uint32_t *const gd_tiles[GD_TILE_COUNT];

/* Source stride handed to z_fb_hw_blit_mem(). MUST be 4 --
 * see gen_sprites.py's header for what a 2-byte stride does
 * to the blitter's row walk. */
#define GD_TILE_STRIDE 4

/* Sprites carry a DATA plane and a MASK plane, because
 * gpu_blit.v's copy mode has no raster op and would draw an
 * opaque box. Composited in software as
 * (dst & ~mask) | data -- see gamedemo.c's spr_draw(). */
extern const uint16_t gd_spr_mouse_stand[GD_SPR_H];
extern const uint16_t gd_msk_mouse_stand[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_stand[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_stand[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_stand_m[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_stand_m[GD_SPR_H];
extern const uint16_t gd_spr_mouse_run1[GD_SPR_H];
extern const uint16_t gd_msk_mouse_run1[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_run1[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_run1[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_run1_m[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_run1_m[GD_SPR_H];
extern const uint16_t gd_spr_mouse_run2[GD_SPR_H];
extern const uint16_t gd_msk_mouse_run2[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_run2[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_run2[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_run2_m[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_run2_m[GD_SPR_H];
extern const uint16_t gd_spr_mouse_jump[GD_SPR_H];
extern const uint16_t gd_msk_mouse_jump[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_jump[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_jump[GD_SPR_H];
extern const uint32_t gd_hspr_mouse_jump_m[GD_SPR_H];
extern const uint32_t gd_hmsk_mouse_jump_m[GD_SPR_H];
extern const uint16_t gd_spr_cat1[GD_SPR_H];
extern const uint16_t gd_msk_cat1[GD_SPR_H];
extern const uint32_t gd_hspr_cat1[GD_SPR_H];
extern const uint32_t gd_hmsk_cat1[GD_SPR_H];
extern const uint32_t gd_hspr_cat1_m[GD_SPR_H];
extern const uint32_t gd_hmsk_cat1_m[GD_SPR_H];
extern const uint16_t gd_spr_cat2[GD_SPR_H];
extern const uint16_t gd_msk_cat2[GD_SPR_H];
extern const uint32_t gd_hspr_cat2[GD_SPR_H];
extern const uint32_t gd_hmsk_cat2[GD_SPR_H];
extern const uint32_t gd_hspr_cat2_m[GD_SPR_H];
extern const uint32_t gd_hmsk_cat2_m[GD_SPR_H];
extern const uint16_t gd_spr_cloud_l[GD_SPR_H];
extern const uint16_t gd_msk_cloud_l[GD_SPR_H];
extern const uint32_t gd_hspr_cloud_l[GD_SPR_H];
extern const uint32_t gd_hmsk_cloud_l[GD_SPR_H];
extern const uint32_t gd_hspr_cloud_l_m[GD_SPR_H];
extern const uint32_t gd_hmsk_cloud_l_m[GD_SPR_H];
extern const uint16_t gd_spr_cloud_r[GD_SPR_H];
extern const uint16_t gd_msk_cloud_r[GD_SPR_H];
extern const uint32_t gd_hspr_cloud_r[GD_SPR_H];
extern const uint32_t gd_hmsk_cloud_r[GD_SPR_H];
extern const uint32_t gd_hspr_cloud_r_m[GD_SPR_H];
extern const uint32_t gd_hmsk_cloud_r_m[GD_SPR_H];
extern const uint16_t gd_spr_tree_top[GD_SPR_H];
extern const uint16_t gd_msk_tree_top[GD_SPR_H];
extern const uint32_t gd_hspr_tree_top[GD_SPR_H];
extern const uint32_t gd_hmsk_tree_top[GD_SPR_H];
extern const uint32_t gd_hspr_tree_top_m[GD_SPR_H];
extern const uint32_t gd_hmsk_tree_top_m[GD_SPR_H];
extern const uint16_t gd_spr_tree_bot[GD_SPR_H];
extern const uint16_t gd_msk_tree_bot[GD_SPR_H];
extern const uint32_t gd_hspr_tree_bot[GD_SPR_H];
extern const uint32_t gd_hmsk_tree_bot[GD_SPR_H];
extern const uint32_t gd_hspr_tree_bot_m[GD_SPR_H];
extern const uint32_t gd_hmsk_tree_bot_m[GD_SPR_H];
extern const uint16_t gd_spr_bird1[GD_SPR_H];
extern const uint16_t gd_msk_bird1[GD_SPR_H];
extern const uint32_t gd_hspr_bird1[GD_SPR_H];
extern const uint32_t gd_hmsk_bird1[GD_SPR_H];
extern const uint32_t gd_hspr_bird1_m[GD_SPR_H];
extern const uint32_t gd_hmsk_bird1_m[GD_SPR_H];
extern const uint16_t gd_spr_bird2[GD_SPR_H];
extern const uint16_t gd_msk_bird2[GD_SPR_H];
extern const uint32_t gd_hspr_bird2[GD_SPR_H];
extern const uint32_t gd_hmsk_bird2[GD_SPR_H];
extern const uint32_t gd_hspr_bird2_m[GD_SPR_H];
extern const uint32_t gd_hmsk_bird2_m[GD_SPR_H];

#endif
