/*
 * Zeitlos
 * Copyright (c) 2025 Lone Dynamics Corporation. All rights reserved.
 *
 * See zkbd.h, and docs/keyboard_layouts.md. The layout tables are in
 * zkbd_layouts.c, generated by tools/gen_kbd_layouts.py.
 */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>

#include "zkbd.h"

// -- layout lookup --

static char lower_ascii(char c) {
	return (c >= 'A' && c <= 'Z') ? (char)(c + 32) : c;
}

int z_kbd_layout_find(const char *name) {

	if (!name) return -1;

	for (int i = 0; i < z_kbd_layout_count && i < Z_KBD_LAYOUT_MAX; i++) {
		const char *a = z_kbd_layouts[i].name, *b = name;
		while (*a && *b && lower_ascii(*a) == lower_ascii(*b)) { a++; b++; }
		if (!*a && !*b) return i;
	}

	return -1;

}

const z_kbd_layout_t *z_kbd_layout_info(int id) {
	if (id < 0 || id >= z_kbd_layout_count) id = 0;
	return &z_kbd_layouts[id];
}

static const z_kbd_key_t *find_key(const z_kbd_layout_t *l, uint8_t usage) {

	// ~50 entries, sorted: a binary search is four or five probes.
	int lo = 0, hi = (int)l->nkeys - 1;
	while (lo <= hi) {
		int mid = (lo + hi) / 2;
		if (l->keys[mid].usage == usage) return &l->keys[mid];
		if (l->keys[mid].usage < usage) lo = mid + 1;
		else hi = mid - 1;
	}
	return NULL;

}

// -- case --
//
// Caps Lock acts on a key whose two levels are a lower/upper case pair.
// That has to be decided from the characters, not from the key's
// position: a-umlaut is a letter on German and a punctuation position
// on US. These are the pairs the layouts can produce.

static bool case_pair(uint32_t lo, uint32_t up) {

	if (lo >= 'a' && lo <= 'z') return up == lo - 32;
	// Latin-1: 0xE0-0xFE lower, 0xC0-0xDE upper, except the division
	// and multiplication signs at 0xF7/0xD7.
	if (lo >= 0xE0 && lo <= 0xFE && lo != 0xF7) return up == lo - 32;
	// Latin Extended-A: mostly pairs at (even upper, odd lower).
	if (lo >= 0x0100 && lo <= 0x017F) return up + 1 == lo || up == lo - 1;
	// Greek and Cyrillic, for the day a layout has them.
	if (lo >= 0x03B1 && lo <= 0x03C9) return up == lo - 32;
	if (lo >= 0x0430 && lo <= 0x044F) return up == lo - 32;
	return false;

}

// -- keys that are the same on every layout --

static uint32_t fixed_key(uint8_t usage, char kp_decimal) {

	switch (usage) {

		case 0x28: return 0x0d;   // Enter -> CR
		case 0x29: return 0x1b;   // Escape
		case 0x2A: return 0x7f;   // Backspace -- DEL, matching zeitlos.c's
		                          // readline(), which accepts either CH_BS
		                          // or CH_DEL
		case 0x2B: return '\t';   // Tab
		case 0x2C: return ' ';    // Space

		case 0x3A: return Z_KEY_F1;
		case 0x3B: return Z_KEY_F2;
		case 0x3C: return Z_KEY_F3;
		case 0x3D: return Z_KEY_F4;
		case 0x3E: return Z_KEY_F5;
		case 0x3F: return Z_KEY_F6;
		case 0x40: return Z_KEY_F7;
		case 0x41: return Z_KEY_F8;
		case 0x42: return Z_KEY_F9;
		case 0x43: return Z_KEY_F10;
		case 0x44: return Z_KEY_F11;
		case 0x45: return Z_KEY_F12;

		case 0x49: return Z_KEY_INSERT;
		case 0x4A: return Z_KEY_HOME;
		case 0x4B: return Z_KEY_PAGEUP;
		case 0x4C: return Z_KEY_DELETE;
		case 0x4D: return Z_KEY_END;
		case 0x4E: return Z_KEY_PAGEDOWN;
		case 0x4F: return Z_KEY_RIGHT;
		case 0x50: return Z_KEY_LEFT;
		case 0x51: return Z_KEY_DOWN;
		case 0x52: return Z_KEY_UP;

		// The keypad types digits and operators whatever the Num Lock
		// state (zkbd.h, "lock keys", on why Num Lock starts off). Its
		// decimal key follows the layout: a comma on German.
		case 0x54: return '/';
		case 0x55: return '*';
		case 0x56: return '-';
		case 0x57: return '+';
		case 0x58: return 0x0d;   // keypad Enter
		case 0x59: case 0x5A: case 0x5B: case 0x5C: case 0x5D:
		case 0x5E: case 0x5F: case 0x60: case 0x61:
			return (uint32_t)('1' + (usage - 0x59));
		case 0x62: return '0';
		case 0x63: return (uint32_t)(unsigned char)kp_decimal;
		case 0x67: return '=';    // keypad = (Mac keyboards)

		default: return Z_KEY_NONE;

	}

}

// -- translation --

uint32_t z_kbd_translate(int layout, uint8_t usage, uint8_t modifiers,
	uint8_t locks, uint8_t *mods_out) {

	const z_kbd_layout_t *l = z_kbd_layout_info(layout);

	if (mods_out) *mods_out = modifiers;

	// Bare modifiers (and the pseudo-usages sw/os/hid.c synthesises for
	// them) have no keysym.
	if (usage >= 0xE0) return Z_KEY_NONE;

	const z_kbd_key_t *k = find_key(l, usage);
	if (!k) return fixed_key(usage, l->kp_decimal ? l->kp_decimal : '.');

	bool shift = (modifiers & Z_KBD_MOD_SHIFT) != 0;
	bool ctrl  = (modifiers & Z_KBD_MOD_CTRL) != 0;
	bool altgr = l->altgr && (modifiers & Z_KBD_MOD_RALT) != 0;
	bool caps  = (locks & Z_KBD_LOCK_CAPS) != 0;

	// A key with nothing on its AltGr levels behaves as if AltGr were
	// not held: plain or shifted character, right Alt left in place.
	if (altgr && !k->sym[2] && !k->sym[3]) altgr = false;

	int base = altgr ? 2 : 0;
	bool up = shift;
	if (caps && case_pair(k->sym[base], k->sym[base + 1])) up = !up;

	uint32_t v = k->sym[base + (up ? 1 : 0)];
	// A level xkb leaves empty on an otherwise-used key types nothing.
	if (!v) return Z_KEY_NONE;

	if (altgr && mods_out) *mods_out = (uint8_t)(modifiers & ~Z_KBD_MOD_RALT);

	// Ctrl + a key whose plain character is a Latin letter: the control
	// code for that letter, whatever Shift, Caps Lock or AltGr say --
	// the same rule as before layouts, applied to the layout's letter.
	uint32_t plain = k->sym[0];
	if (ctrl && !altgr) {
		if (plain >= 'a' && plain <= 'z') return plain - 'a' + 1;
		if (plain >= 'A' && plain <= 'Z') return plain - 'A' + 1;
	}

	if (v >= Z_KBD_DEAD_BASE && v < Z_KBD_DEAD_BASE + 0x100)
		return Z_KEY_DEAD(v - Z_KBD_DEAD_BASE);

	return v;

}

uint32_t z_kbd_event_to_keysym(int32_t ev, uint8_t *mods_out) {
	return z_kbd_translate((int)Z_KBD_EV_LAYOUT(ev), Z_KBD_EV_USAGE(ev),
		Z_KBD_EV_MODS(ev), (uint8_t)Z_KBD_EV_LOCKS(ev), mods_out);
}

uint32_t z_kbd_usage_to_keysym(uint8_t usage, uint8_t modifiers) {
	return z_kbd_translate(0, usage, modifiers, 0, NULL);
}

// -- dead keys --

uint32_t z_kbd_compose(uint32_t dead, uint32_t cp) {

	if (!Z_KEY_IS_DEAD(dead) || cp > 0xFFFF) return 0;

	uint16_t d = (uint16_t)(Z_KBD_DEAD_BASE + (dead - Z_KEY_DEAD_BASE));
	uint16_t b = (uint16_t)cp;

	int lo = 0, hi = z_kbd_compose_count - 1;
	while (lo <= hi) {
		int mid = (lo + hi) / 2;
		const z_kbd_compose_t *e = &z_kbd_compose_table[mid];
		if (e->dead == d && e->base == b) return e->result;
		if (e->dead < d || (e->dead == d && e->base < b)) lo = mid + 1;
		else hi = mid - 1;
	}
	return 0;

}

uint32_t z_kbd_dead_spacing_of(uint32_t dead) {
	if (!Z_KEY_IS_DEAD(dead)) return 0;
	uint32_t n = dead - Z_KEY_DEAD_BASE;
	if (n >= (uint32_t)z_kbd_dead_count) return 0;
	return z_kbd_dead_spacing[n];
}

// -- input methods: romaji to kana -- see zkbd.h --

typedef struct {
	const char	*romaji;
	uint16_t	kana[2];	// hiragana (or punctuation); [1] 0 if one
} z_kbd_romaji_t;

// Generated (docs/keyboard_layouts.md, "Japanese input"), sorted by
// the romaji string.
static const z_kbd_romaji_t romaji[] = {
	{ ",", { 0x3001, 0x0000 } },	// 、
	{ "-", { 0x30fc, 0x0000 } },	// ー
	{ ".", { 0x3002, 0x0000 } },	// 。
	{ "/", { 0x30fb, 0x0000 } },	// ・
	{ "[", { 0x300c, 0x0000 } },	// 「
	{ "]", { 0x300d, 0x0000 } },	// 」
	{ "a", { 0x3042, 0x0000 } },	// あ
	{ "ba", { 0x3070, 0x0000 } },	// ば
	{ "be", { 0x3079, 0x0000 } },	// べ
	{ "bi", { 0x3073, 0x0000 } },	// び
	{ "bo", { 0x307c, 0x0000 } },	// ぼ
	{ "bu", { 0x3076, 0x0000 } },	// ぶ
	{ "bya", { 0x3073, 0x3083 } },	// びゃ
	{ "byo", { 0x3073, 0x3087 } },	// びょ
	{ "byu", { 0x3073, 0x3085 } },	// びゅ
	{ "cha", { 0x3061, 0x3083 } },	// ちゃ
	{ "che", { 0x3061, 0x3047 } },	// ちぇ
	{ "chi", { 0x3061, 0x0000 } },	// ち
	{ "cho", { 0x3061, 0x3087 } },	// ちょ
	{ "chu", { 0x3061, 0x3085 } },	// ちゅ
	{ "cya", { 0x3061, 0x3083 } },	// ちゃ
	{ "cye", { 0x3061, 0x3047 } },	// ちぇ
	{ "cyo", { 0x3061, 0x3087 } },	// ちょ
	{ "cyu", { 0x3061, 0x3085 } },	// ちゅ
	{ "da", { 0x3060, 0x0000 } },	// だ
	{ "de", { 0x3067, 0x0000 } },	// で
	{ "dhi", { 0x3067, 0x3043 } },	// でぃ
	{ "di", { 0x3062, 0x0000 } },	// ぢ
	{ "do", { 0x3069, 0x0000 } },	// ど
	{ "du", { 0x3065, 0x0000 } },	// づ
	{ "dwu", { 0x3069, 0x3045 } },	// どぅ
	{ "dya", { 0x3062, 0x3083 } },	// ぢゃ
	{ "dyo", { 0x3062, 0x3087 } },	// ぢょ
	{ "dyu", { 0x3062, 0x3085 } },	// ぢゅ
	{ "e", { 0x3048, 0x0000 } },	// え
	{ "fa", { 0x3075, 0x3041 } },	// ふぁ
	{ "fe", { 0x3075, 0x3047 } },	// ふぇ
	{ "fi", { 0x3075, 0x3043 } },	// ふぃ
	{ "fo", { 0x3075, 0x3049 } },	// ふぉ
	{ "fu", { 0x3075, 0x0000 } },	// ふ
	{ "ga", { 0x304c, 0x0000 } },	// が
	{ "ge", { 0x3052, 0x0000 } },	// げ
	{ "gi", { 0x304e, 0x0000 } },	// ぎ
	{ "go", { 0x3054, 0x0000 } },	// ご
	{ "gu", { 0x3050, 0x0000 } },	// ぐ
	{ "gya", { 0x304e, 0x3083 } },	// ぎゃ
	{ "gyo", { 0x304e, 0x3087 } },	// ぎょ
	{ "gyu", { 0x304e, 0x3085 } },	// ぎゅ
	{ "ha", { 0x306f, 0x0000 } },	// は
	{ "he", { 0x3078, 0x0000 } },	// へ
	{ "hi", { 0x3072, 0x0000 } },	// ひ
	{ "ho", { 0x307b, 0x0000 } },	// ほ
	{ "hu", { 0x3075, 0x0000 } },	// ふ
	{ "hya", { 0x3072, 0x3083 } },	// ひゃ
	{ "hyo", { 0x3072, 0x3087 } },	// ひょ
	{ "hyu", { 0x3072, 0x3085 } },	// ひゅ
	{ "i", { 0x3044, 0x0000 } },	// い
	{ "ja", { 0x3058, 0x3083 } },	// じゃ
	{ "je", { 0x3058, 0x3047 } },	// じぇ
	{ "ji", { 0x3058, 0x0000 } },	// じ
	{ "jo", { 0x3058, 0x3087 } },	// じょ
	{ "ju", { 0x3058, 0x3085 } },	// じゅ
	{ "jya", { 0x3058, 0x3083 } },	// じゃ
	{ "jye", { 0x3058, 0x3047 } },	// じぇ
	{ "jyo", { 0x3058, 0x3087 } },	// じょ
	{ "jyu", { 0x3058, 0x3085 } },	// じゅ
	{ "ka", { 0x304b, 0x0000 } },	// か
	{ "ke", { 0x3051, 0x0000 } },	// け
	{ "ki", { 0x304d, 0x0000 } },	// き
	{ "ko", { 0x3053, 0x0000 } },	// こ
	{ "ku", { 0x304f, 0x0000 } },	// く
	{ "kya", { 0x304d, 0x3083 } },	// きゃ
	{ "kyo", { 0x304d, 0x3087 } },	// きょ
	{ "kyu", { 0x304d, 0x3085 } },	// きゅ
	{ "la", { 0x3041, 0x0000 } },	// ぁ
	{ "le", { 0x3047, 0x0000 } },	// ぇ
	{ "li", { 0x3043, 0x0000 } },	// ぃ
	{ "lka", { 0x3095, 0x0000 } },	// ゕ
	{ "lke", { 0x3096, 0x0000 } },	// ゖ
	{ "lo", { 0x3049, 0x0000 } },	// ぉ
	{ "ltsu", { 0x3063, 0x0000 } },	// っ
	{ "ltu", { 0x3063, 0x0000 } },	// っ
	{ "lu", { 0x3045, 0x0000 } },	// ぅ
	{ "lwa", { 0x308e, 0x0000 } },	// ゎ
	{ "lya", { 0x3083, 0x0000 } },	// ゃ
	{ "lyo", { 0x3087, 0x0000 } },	// ょ
	{ "lyu", { 0x3085, 0x0000 } },	// ゅ
	{ "ma", { 0x307e, 0x0000 } },	// ま
	{ "me", { 0x3081, 0x0000 } },	// め
	{ "mi", { 0x307f, 0x0000 } },	// み
	{ "mo", { 0x3082, 0x0000 } },	// も
	{ "mu", { 0x3080, 0x0000 } },	// む
	{ "mya", { 0x307f, 0x3083 } },	// みゃ
	{ "myo", { 0x307f, 0x3087 } },	// みょ
	{ "myu", { 0x307f, 0x3085 } },	// みゅ
	{ "n\'", { 0x3093, 0x0000 } },	// ん
	{ "na", { 0x306a, 0x0000 } },	// な
	{ "ne", { 0x306d, 0x0000 } },	// ね
	{ "ni", { 0x306b, 0x0000 } },	// に
	{ "nn", { 0x3093, 0x0000 } },	// ん
	{ "no", { 0x306e, 0x0000 } },	// の
	{ "nu", { 0x306c, 0x0000 } },	// ぬ
	{ "nya", { 0x306b, 0x3083 } },	// にゃ
	{ "nyo", { 0x306b, 0x3087 } },	// にょ
	{ "nyu", { 0x306b, 0x3085 } },	// にゅ
	{ "o", { 0x304a, 0x0000 } },	// お
	{ "pa", { 0x3071, 0x0000 } },	// ぱ
	{ "pe", { 0x307a, 0x0000 } },	// ぺ
	{ "pi", { 0x3074, 0x0000 } },	// ぴ
	{ "po", { 0x307d, 0x0000 } },	// ぽ
	{ "pu", { 0x3077, 0x0000 } },	// ぷ
	{ "pya", { 0x3074, 0x3083 } },	// ぴゃ
	{ "pyo", { 0x3074, 0x3087 } },	// ぴょ
	{ "pyu", { 0x3074, 0x3085 } },	// ぴゅ
	{ "ra", { 0x3089, 0x0000 } },	// ら
	{ "re", { 0x308c, 0x0000 } },	// れ
	{ "ri", { 0x308a, 0x0000 } },	// り
	{ "ro", { 0x308d, 0x0000 } },	// ろ
	{ "ru", { 0x308b, 0x0000 } },	// る
	{ "rya", { 0x308a, 0x3083 } },	// りゃ
	{ "ryo", { 0x308a, 0x3087 } },	// りょ
	{ "ryu", { 0x308a, 0x3085 } },	// りゅ
	{ "sa", { 0x3055, 0x0000 } },	// さ
	{ "se", { 0x305b, 0x0000 } },	// せ
	{ "sha", { 0x3057, 0x3083 } },	// しゃ
	{ "she", { 0x3057, 0x3047 } },	// しぇ
	{ "shi", { 0x3057, 0x0000 } },	// し
	{ "sho", { 0x3057, 0x3087 } },	// しょ
	{ "shu", { 0x3057, 0x3085 } },	// しゅ
	{ "si", { 0x3057, 0x0000 } },	// し
	{ "so", { 0x305d, 0x0000 } },	// そ
	{ "su", { 0x3059, 0x0000 } },	// す
	{ "sya", { 0x3057, 0x3083 } },	// しゃ
	{ "sye", { 0x3057, 0x3047 } },	// しぇ
	{ "syo", { 0x3057, 0x3087 } },	// しょ
	{ "syu", { 0x3057, 0x3085 } },	// しゅ
	{ "ta", { 0x305f, 0x0000 } },	// た
	{ "te", { 0x3066, 0x0000 } },	// て
	{ "thi", { 0x3066, 0x3043 } },	// てぃ
	{ "ti", { 0x3061, 0x0000 } },	// ち
	{ "to", { 0x3068, 0x0000 } },	// と
	{ "tsa", { 0x3064, 0x3041 } },	// つぁ
	{ "tse", { 0x3064, 0x3047 } },	// つぇ
	{ "tsi", { 0x3064, 0x3043 } },	// つぃ
	{ "tso", { 0x3064, 0x3049 } },	// つぉ
	{ "tsu", { 0x3064, 0x0000 } },	// つ
	{ "tu", { 0x3064, 0x0000 } },	// つ
	{ "twu", { 0x3068, 0x3045 } },	// とぅ
	{ "tya", { 0x3061, 0x3083 } },	// ちゃ
	{ "tye", { 0x3061, 0x3047 } },	// ちぇ
	{ "tyo", { 0x3061, 0x3087 } },	// ちょ
	{ "tyu", { 0x3061, 0x3085 } },	// ちゅ
	{ "u", { 0x3046, 0x0000 } },	// う
	{ "va", { 0x3094, 0x3041 } },	// ゔぁ
	{ "ve", { 0x3094, 0x3047 } },	// ゔぇ
	{ "vi", { 0x3094, 0x3043 } },	// ゔぃ
	{ "vo", { 0x3094, 0x3049 } },	// ゔぉ
	{ "vu", { 0x3094, 0x0000 } },	// ゔ
	{ "wa", { 0x308f, 0x0000 } },	// わ
	{ "we", { 0x3046, 0x3047 } },	// うぇ
	{ "wi", { 0x3046, 0x3043 } },	// うぃ
	{ "wo", { 0x3092, 0x0000 } },	// を
	{ "wu", { 0x3046, 0x0000 } },	// う
	{ "xa", { 0x3041, 0x0000 } },	// ぁ
	{ "xe", { 0x3047, 0x0000 } },	// ぇ
	{ "xi", { 0x3043, 0x0000 } },	// ぃ
	{ "xka", { 0x3095, 0x0000 } },	// ゕ
	{ "xke", { 0x3096, 0x0000 } },	// ゖ
	{ "xo", { 0x3049, 0x0000 } },	// ぉ
	{ "xtsu", { 0x3063, 0x0000 } },	// っ
	{ "xtu", { 0x3063, 0x0000 } },	// っ
	{ "xu", { 0x3045, 0x0000 } },	// ぅ
	{ "xwa", { 0x308e, 0x0000 } },	// ゎ
	{ "xya", { 0x3083, 0x0000 } },	// ゃ
	{ "xyo", { 0x3087, 0x0000 } },	// ょ
	{ "xyu", { 0x3085, 0x0000 } },	// ゅ
	{ "ya", { 0x3084, 0x0000 } },	// や
	{ "ye", { 0x3044, 0x3047 } },	// いぇ
	{ "yo", { 0x3088, 0x0000 } },	// よ
	{ "yu", { 0x3086, 0x0000 } },	// ゆ
	{ "za", { 0x3056, 0x0000 } },	// ざ
	{ "ze", { 0x305c, 0x0000 } },	// ぜ
	{ "zi", { 0x3058, 0x0000 } },	// じ
	{ "zo", { 0x305e, 0x0000 } },	// ぞ
	{ "zu", { 0x305a, 0x0000 } },	// ず
	{ "zya", { 0x3058, 0x3083 } },	// じゃ
	{ "zye", { 0x3058, 0x3047 } },	// じぇ
	{ "zyo", { 0x3058, 0x3087 } },	// じょ
	{ "zyu", { 0x3058, 0x3085 } },	// じゅ
	{ "~", { 0x301c, 0x0000 } },	// 〜
};

#define ROMAJI_N ((int)(sizeof(romaji) / sizeof(romaji[0])))

static const z_kbd_romaji_t *romaji_exact(const char *s) {
	int lo = 0, hi = ROMAJI_N - 1;
	while (lo <= hi) {
		int mid = (lo + hi) / 2;
		int c = strcmp(romaji[mid].romaji, s);
		if (!c) return &romaji[mid];
		if (c < 0) lo = mid + 1;
		else hi = mid - 1;
	}
	return NULL;
}

// True if some entry is LONGER than `s` and starts with it -- the
// letters could still grow into it, so they wait.
static bool romaji_prefix(const char *s, int n) {
	for (int i = 0; i < ROMAJI_N; i++)
		if (!strncmp(romaji[i].romaji, s, (size_t)n) && romaji[i].romaji[n])
			return true;
	return false;
}

static uint32_t kana_out(const z_kbd_ime_t *ime, uint16_t cp) {
	// Katakana is hiragana shifted by 0x60, U+3041-U+3096 -> U+30A1-U+30F6.
	if (ime->mode == Z_KBD_IME_KATAKANA && cp >= 0x3041 && cp <= 0x3096)
		return (uint32_t)cp + 0x60;
	return cp;
}

static int emit_entry(const z_kbd_ime_t *ime, const z_kbd_romaji_t *e, uint32_t *out) {
	int k = 0;
	out[k++] = kana_out(ime, e->kana[0]);
	if (e->kana[1]) out[k++] = kana_out(ime, e->kana[1]);
	return k;
}

static void pend_drop(z_kbd_ime_t *ime, int k) {
	for (int i = k; i <= ime->n; i++) ime->pend[i - k] = ime->pend[i];
	ime->n = (uint8_t)(ime->n - k);
}

static bool is_vowel(char c) {
	return c == 'a' || c == 'i' || c == 'u' || c == 'e' || c == 'o';
}

bool z_kbd_ime_takes(uint32_t cp) {
	if ((cp >= 'a' && cp <= 'z') || (cp >= 'A' && cp <= 'Z')) return true;
	// The apostrophe too: after n it is the syllabic n (n'), and
	// z_kbd_ime_feed() passes it through as itself anywhere else. It
	// has to reach the converter to find out which.
	if (cp == '\'') return true;
	char s[2] = { (char)cp, 0 };
	return cp < 0x80 && romaji_exact(s) != NULL;
}

int z_kbd_ime_flush(z_kbd_ime_t *ime, uint32_t *out) {

	int k = 0;
	if ((ime->n == 1 && ime->pend[0] == 'n') ||
	    (ime->n == 2 && ime->pend[0] == 'n' && ime->pend[1] == 'n')) {
		out[k++] = kana_out(ime, 0x3093);				// ん
	} else {
		for (int i = 0; i < ime->n; i++) out[k++] = (uint8_t)ime->pend[i];
	}
	ime->n = 0;
	ime->pend[0] = 0;
	return k;

}

int z_kbd_ime_feed(z_kbd_ime_t *ime, uint32_t cp, uint32_t *out) {

	int k = 0;

	if (cp >= 'A' && cp <= 'Z') cp += 32;		// case does not change a kana

	// Punctuation stands alone: whatever is pending finishes first.
	if (!(cp >= 'a' && cp <= 'z') && cp != '\'') {
		k = z_kbd_ime_flush(ime, out);
		char s[2] = { (char)cp, 0 };
		const z_kbd_romaji_t *e = romaji_exact(s);
		if (e) k += emit_entry(ime, e, out + k);
		return k;
	}

	// n' is the syllabic n; an apostrophe anywhere else is itself.
	if (cp == '\'' && !(ime->n == 1 && ime->pend[0] == 'n')) {
		k = z_kbd_ime_flush(ime, out);
		out[k++] = '\'';
		return k;
	}

	if (ime->n >= Z_KBD_IME_PEND) k += z_kbd_ime_flush(ime, out);
	ime->pend[ime->n++] = (char)cp;
	ime->pend[ime->n] = 0;

	for (;;) {

		if (!ime->n) return k;

		// nn: the syllabic n -- but the second n may begin the next
		// syllable, as in konna (こんな), which is how the common
		// Japanese input methods read it. So nn waits for one more
		// letter: a vowel or y takes the second n with it.
		if (ime->n >= 2 && ime->pend[0] == 'n' && ime->pend[1] == 'n') {
			if (ime->n == 2) return k;
			out[k++] = kana_out(ime, 0x3093);			// ん
			char c2 = ime->pend[2];
			pend_drop(ime, (is_vowel(c2) || c2 == 'y') ? 1 : 2);
			continue;
		}

		const z_kbd_romaji_t *e = romaji_exact(ime->pend);
		bool longer = romaji_prefix(ime->pend, ime->n);

		if (e && !longer) {
			k += emit_entry(ime, e, out + k);
			ime->n = 0;
			ime->pend[0] = 0;
			return k;
		}
		if (longer) return k;					// could still become one

		char c0 = ime->pend[0], c1 = ime->n > 1 ? ime->pend[1] : 0;

		// kk, tt, ss ...: the small tsu, and the second letter goes on.
		if (c1 == c0 && !is_vowel(c0) && c0 != 'n') {
			out[k++] = kana_out(ime, 0x3063);			// っ
			pend_drop(ime, 1);
			continue;
		}

		// n before anything that cannot follow it in a syllable.
		if (c0 == 'n' && c1 && !is_vowel(c1) && c1 != 'y') {
			out[k++] = kana_out(ime, 0x3093);			// ん
			pend_drop(ime, 1);
			continue;
		}

		// Nothing will come of the first letter: it is itself.
		out[k++] = (uint8_t)c0;
		pend_drop(ime, 1);

	}

}

bool z_kbd_ime_backspace(z_kbd_ime_t *ime) {
	if (!ime->n) return false;
	ime->pend[--ime->n] = 0;
	return true;
}

// -- the tables --
//
// Generated (tools/gen_kbd_layouts.py) and included here rather than
// compiled on its own, so that every Makefile that already builds
// zkbd.o gets the layouts with no change: the app Makefiles list their
// common objects by hand.
#include "zkbd_layouts.c"
