/*
 * Host test for authkeys.c: the /user/authkeys parser, and signature
 * checking with real keys. The keys were generated by OpenSSL; every
 * expected value in tests/authkeys_keys.h -- the authorized_keys lines,
 * the SHA256: fingerprints, an RSA signature made by hand with pow() --
 * was computed by Python, independently of the code under test.
 *
 *   make test
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

#include "../authkeys.h"
#include "../../ssh/ssh_wire.h"
#include "../../../../ext/monocypher/monocypher.h"
#include "../../../../ext/monocypher/monocypher-ed25519.h"
#include "../../../web/bignum.h"
#include "authkeys_keys.h"

static int checks, fails;
#define CK(c, ...) do { checks++; if (!(c)) { fails++; printf("FAIL %d: ", __LINE__); \
	printf(__VA_ARGS__); printf("\n"); } } while (0)

static int warned;
static char last_why[128];
static void warn(int line, const char *why) {
	warned++;
	snprintf(last_why, sizeof(last_why), "line %d: %s", line, why);
}

static char file[8192];

int main(void) {
	authkeys_t ak;
	char fp[64];
	uint8_t sig[128];

	// -- the file, every kind of line --
	int n = snprintf(file, sizeof(file),
		"# my keys\r\n"
		"%s\r\n"
		"\n"
		"   %s\n"
		"%s the desktop, by fingerprint\n"
		"%s\n"
		"from=\"10.0.0.1\" %s\n"
		"%s\n"
		"ssh-ed25519 !!!notbase64!!!\n"
		"ssh-dss AAAAB3NzaC1kc3MAAACBAP\n"
		"SHA256:tooshort\n",
		ED_LINE, RSA_LINE, ED_FP, ED_FP_HEX, ED_LINE, RSA1024_LINE);
	warned = 0;
	authkeys_parse(&ak, file, (uint32_t)n, warn);
	CK(ak.n == 4, "four entries: ed25519, rsa, a SHA256: fingerprint, a hex one (%d)", ak.n);
	CK(ak.refused == 5 && warned == 5, "five refused, each reported (%d, %d)", ak.refused, warned);

	// -- matching --
	CK(authkeys_allows(&ak, "ssh-ed25519", ED_BLOB, sizeof(ED_BLOB)), "the ed25519 key logs in");
	CK(authkeys_allows(&ak, "rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB)), "the RSA key logs in");
	CK(!authkeys_allows(&ak, "ssh-ed25519", RSA_BLOB, sizeof(RSA_BLOB)), "an RSA key under the ed25519 name does not");
	CK(!authkeys_allows(&ak, "rsa-sha2-512", RSA_BLOB, sizeof(RSA_BLOB)), "nor under an algorithm we do not offer");
	CK(!authkeys_allows(&ak, "ssh-rsa", RSA_BLOB, sizeof(RSA_BLOB)), "nor with SHA-1 ssh-rsa");
	{
		uint8_t other[sizeof(ED_BLOB)];
		memcpy(other, ED_BLOB, sizeof(other));
		other[sizeof(other) - 1] ^= 1;
		CK(!authkeys_allows(&ak, "ssh-ed25519", other, sizeof(other)), "a key one bit different does not");
	}
	{
		authkeys_t only_fp;
		char f2[128];
		int m = snprintf(f2, sizeof(f2), "%s\n", ED_FP);
		authkeys_parse(&only_fp, f2, (uint32_t)m, NULL);
		CK(only_fp.n == 1 && authkeys_allows(&only_fp, "ssh-ed25519", ED_BLOB, sizeof(ED_BLOB)),
			"a fingerprint line alone lets its key in");
		CK(!authkeys_allows(&only_fp, "rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB)), "and no other");
		authkeys_parse(&only_fp, "", 0, NULL);
		CK(only_fp.n == 0 && !authkeys_allows(&only_fp, "ssh-ed25519", ED_BLOB, sizeof(ED_BLOB)),
			"an empty file lets nothing in");
	}

	// -- fingerprints, as ssh-keygen -lf prints them --
	authkeys_fingerprint(fp, sizeof(fp), ED_BLOB, sizeof(ED_BLOB));
	CK(!strcmp(fp, ED_FP), "ed25519 fingerprint %s == %s", fp, ED_FP);
	authkeys_fingerprint(fp, sizeof(fp), RSA_BLOB, sizeof(RSA_BLOB));
	CK(!strcmp(fp, RSA_FP), "RSA fingerprint %s == %s", fp, RSA_FP);

	// -- blob types --
	{
		uint32_t bits = 0;
		CK(authkeys_blob_type(RSA_BLOB, sizeof(RSA_BLOB), &bits) == AK_RSA && bits == 2048, "RSA, 2048 bits (%u)", bits);
		CK(authkeys_blob_type(ED_BLOB, sizeof(ED_BLOB), NULL) == AK_ED25519, "ed25519");
		CK(authkeys_blob_type(ED_BLOB, sizeof(ED_BLOB) - 1, NULL) < 0, "a truncated blob is neither");
	}

	// -- Ed25519: monocypher and OpenSSL agree on the key --
	{
		uint8_t seed[32], secret[64], pub[32];
		memcpy(seed, ED_SEED, 32);
		crypto_ed25519_key_pair(secret, pub, seed);
		CK(!memcmp(pub, ED_PUB, 32), "the same seed gives OpenSSL's public key");
		uint8_t s64[64];
		crypto_ed25519_sign(s64, secret, (const uint8_t *)RSA_MSG, strlen(RSA_MSG));
		ssh_wr w;
		ssh_wr_init(&w, sig, sizeof(sig));
		ssh_wr_cstr(&w, "ssh-ed25519");
		ssh_wr_string(&w, s64, 64);
		uint32_t sl = ssh_wr_len(&w);
		CK(authkeys_verify("ssh-ed25519", ED_BLOB, sizeof(ED_BLOB), sig, sl,
			(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "an ed25519 signature verifies");
		CK(!authkeys_verify("ssh-ed25519", ED_BLOB, sizeof(ED_BLOB), sig, sl,
			(const uint8_t *)"the data a client signs!", 24), "over other data it does not");
		sig[sl - 1] ^= 1;
		CK(!authkeys_verify("ssh-ed25519", ED_BLOB, sizeof(ED_BLOB), sig, sl,
			(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "a changed signature does not");
	}

	// -- RSA: a signature Python made by hand --
	CK(authkeys_verify("rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB), RSA_SIGBLOB, sizeof(RSA_SIGBLOB),
		(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "an rsa-sha2-256 signature verifies");
	CK(!authkeys_verify("rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB), RSA_SIGBLOB, sizeof(RSA_SIGBLOB),
		(const uint8_t *)"the data a client signed", 24), "over other data it does not");
	{
		uint8_t bad[sizeof(RSA_SIGBLOB)];
		memcpy(bad, RSA_SIGBLOB, sizeof(bad));
		bad[sizeof(bad) - 5] ^= 0x10;
		CK(!authkeys_verify("rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB), bad, sizeof(bad),
			(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "a changed signature does not");
		memcpy(bad, RSA_SIGBLOB, sizeof(bad));
		memcpy(bad + 4, "rsa-sha2-512", 12);
		CK(!authkeys_verify("rsa-sha2-256", RSA_BLOB, sizeof(RSA_BLOB), bad, sizeof(bad),
			(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "a signature naming another algorithm does not");
		CK(!authkeys_verify("rsa-sha2-256", ED_BLOB, sizeof(ED_BLOB), RSA_SIGBLOB, sizeof(RSA_SIGBLOB),
			(const uint8_t *)RSA_MSG, strlen(RSA_MSG)), "an RSA signature against an ed25519 key does not");
	}

	printf("authkeys: %d checks, %d failed\n", checks, fails);
	return fails != 0;
}
