#!/usr/bin/env python3
"""
Zeitlos -- dice tile generator.

    cd sw/common/games && python3 gen_dice.py

Emits zdice.c / zdice.h: the six faces at two sizes. The generated C is
committed, so this must regenerate identically -- check with `git diff`
after running it.

IN sw/common/games FROM THE START, which is a deliberate exception to
the rule the rest of this directory follows. Cards waited for a second
caller because the shape of the shared thing was a real question --
which of poker's card code was general and which was poker's. A die has
no such question: six faces, pips on a fixed three-by-three grid,
parameterised by size. There is nothing to learn from a second caller
that is not already obvious, and craps will not be the last game here
that rolls one.

Packing matches the card and slot tiles: one uint32_t per row, LEAST
significant bit leftmost, which is what z_fb_hw_blit_mem() expects and
the opposite of the font's MSB-first rows. Both sizes are at most 32
wide, so a row is one word and the stride is 4 bytes.
"""

SIZES = [32, 16]

# The pip grid. Each face names the cells it fills, as (col, row) on a
# three-by-three grid. Written out rather than derived from the number,
# because the arrangement is not a function of the count -- two and
# three both use the diagonal, but six uses the columns rather than
# adding to five.
PIPS = {
    1: [(1, 1)],
    2: [(0, 0), (2, 2)],
    3: [(0, 0), (1, 1), (2, 2)],
    4: [(0, 0), (2, 0), (0, 2), (2, 2)],
    5: [(0, 0), (2, 0), (1, 1), (0, 2), (2, 2)],
    6: [(0, 0), (2, 0), (0, 1), (2, 1), (0, 2), (2, 2)],
}

def face(n, S):
    g = [[0] * S for _ in range(S)]

    def rect(x0, y0, x1, y1, v=1):
        for y in range(max(0, y0), min(S, y1 + 1)):
            for x in range(max(0, x0), min(S, x1 + 1)):
                g[y][x] = v

    def disc(cx, cy, r, v=1):
        for y in range(S):
            for x in range(S):
                dx, dy = x - cx, y - cy
                if dx * dx + dy * dy <= r * r:
                    g[y][x] = v

    # A lit body with dark pips, which is what a real die looks like and
    # also what survives being drawn over anything: the body covers
    # whatever was underneath.
    rect(0, 0, S - 1, S - 1, 1)

    # Corners knocked off, so it reads as a rounded cube rather than a
    # domino. One pixel at 16, two at 32 -- more than that and a small
    # die starts to look like a circle.
    c = 1 if S <= 16 else 2
    for i in range(c):
        for j in range(c - i):
            g[i][j] = 0
            g[i][S - 1 - j] = 0
            g[S - 1 - i][j] = 0
            g[S - 1 - i][S - 1 - j] = 0

    # A dark border just inside the edge, which separates two dice that
    # happen to land next to each other.
    rect(1, 1, S - 2, 1, 0)
    rect(1, S - 2, S - 2, S - 2, 0)
    rect(1, 1, 1, S - 2, 0)
    rect(S - 2, 1, S - 2, S - 2, 0)
    rect(2, 2, S - 3, S - 3, 1)

    # Pips on a three-by-three grid inset from the border.
    inset = max(3, S // 6)
    span = S - 2 * inset
    step = span / 3.0
    pr = max(1, int(step * 0.34))
    for (cx, cy) in PIPS[n]:
        # ROUNDED TO WHOLE PIXELS. A fractional centre makes each disc a
        # slightly different shape depending on where it lands, so the
        # pips are visibly unequal -- and the test that counts them
        # stops being able to say "face n has n times one pip", which is
        # the only cheap way to check a die is right.
        px = int(round(inset + step * (cx + 0.5)))
        py = int(round(inset + step * (cy + 0.5)))
        disc(px, py, pr, 0)

    return g

def pack(g, S):
    out = []
    for y in range(S):
        w = 0
        for x in range(S):
            if g[y][x]:
                w |= 1 << x
        out.append(w)
    return out

def main():
    with open("zdice.h", "w") as f:
        f.write("""#ifndef ZDICE_TILES_H
#define ZDICE_TILES_H

/*
 * Zeitlos -- dice tiles, six faces at two sizes.
 *
 * GENERATED by gen_dice.py. Do not edit; edit the generator and re-run
 * it. The output is committed, so it must regenerate identically.
 *
 * One uint32_t per row with the LEAST significant bit leftmost, the
 * same packing the card and slot tiles use and what z_fb_hw_blit_mem()
 * expects -- the opposite of the font's MSB-first rows. Both sizes are
 * at most 32 wide, so a row is one word.
 *
 * The guard is ZDICE_TILES_H, not ZDICE_H: the obvious name would
 * collide with a size macro, which sw/apps/slots found the hard way.
 *
 * Row r of face n at the big size is z_dice_big[(n - 1) * Z_DICE_BIG + r].
 * Faces are 1 to 6; there is no face 0.
 *
 * The body is LIT and the pips are DARK, which is what a real die looks
 * like and also what makes a die opaque: rolled over anything, it
 * covers it. A dark die with lit pips would need the background cleared
 * first, and clearing is what makes an animation flicker.
 */

#include <stdint.h>

#define Z_DICE_BIG    %d
#define Z_DICE_SMALL  %d
#define Z_DICE_STRIDE 4      /* BYTES per row, as z_fb_hw_blit_mem takes it */
#define Z_DICE_FACES  6

extern const uint32_t z_dice_big[];
extern const uint32_t z_dice_small[];

/* The tile for `face` (1..6) at the given size, or the one face at a
 * size that is not offered. Returns NULL for a face outside 1..6. */
const uint32_t *z_dice_tile(int size, int face);

#endif
""" % (SIZES[0], SIZES[1]))

    with open("zdice.c", "w") as f:
        f.write('/*\n * Zeitlos -- dice tiles.\n *\n'
                ' * GENERATED by gen_dice.py. Do not edit.\n */\n\n'
                '#include "zdice.h"\n')
        for S, nm in zip(SIZES, ("z_dice_big", "z_dice_small")):
            f.write("\nconst uint32_t %s[] = {\n" % nm)
            for n in range(1, 7):
                words = pack(face(n, S), S)
                f.write("\n    /* %d */\n" % n)
                for i in range(0, S, 4):
                    f.write("    " + " ".join("0x%08xu," % w
                            for w in words[i:i + 4]) + "\n")
            f.write("};\n")
        f.write("""
const uint32_t *z_dice_tile(int size, int face)
{
	if (face < 1 || face > Z_DICE_FACES) return 0;

	/* Anything that is not the big size gets the small one. A caller
	 * asking for a size that does not exist wants a die, not a null. */
	if (size >= Z_DICE_BIG)
		return &z_dice_big[(face - 1) * Z_DICE_BIG];

	return &z_dice_small[(face - 1) * Z_DICE_SMALL];
}
""")

    print("wrote zdice.c and zdice.h (%d faces at %s)" %
          (6, " and ".join(str(s) for s in SIZES)))

main()
