#ifndef ZDICE_TILES_H
#define ZDICE_TILES_H

/*
 * Zeitlos -- dice tiles, six faces at two sizes.
 *
 * GENERATED by gen_dice.py. Do not edit; edit the generator and re-run
 * it. The output is committed, so it must regenerate identically.
 *
 * One uint32_t per row with the LEAST significant bit leftmost, the
 * same packing the card and slot tiles use and what z_fb_hw_blit_mem()
 * expects -- the opposite of the font's MSB-first rows. Both sizes are
 * at most 32 wide, so a row is one word.
 *
 * The guard is ZDICE_TILES_H, not ZDICE_H: the obvious name would
 * collide with a size macro, which sw/apps/slots found the hard way.
 *
 * Row r of face n at the big size is z_dice_big[(n - 1) * Z_DICE_BIG + r].
 * Faces are 1 to 6; there is no face 0.
 *
 * The body is LIT and the pips are DARK, which is what a real die looks
 * like and also what makes a die opaque: rolled over anything, it
 * covers it. A dark die with lit pips would need the background cleared
 * first, and clearing is what makes an animation flicker.
 */

#include <stdint.h>

#define Z_DICE_BIG    32
#define Z_DICE_SMALL  16
#define Z_DICE_STRIDE 4      /* BYTES per row, as z_fb_hw_blit_mem takes it */
#define Z_DICE_FACES  6

extern const uint32_t z_dice_big[];
extern const uint32_t z_dice_small[];

/* The tile for `face` (1..6) at the given size, or the one face at a
 * size that is not offered. Returns NULL for a face outside 1..6. */
const uint32_t *z_dice_tile(int size, int face);

#endif
