#!/usr/bin/env python3
"""
Generates libz.sym from the linked blob.

zcc reads this file to learn three things it cannot otherwise know:
where the jump table is, which index each name has, and where the two
words it must patch live. Generated from `nm` output rather than
hand-written, so it cannot disagree with the blob it describes.

Format is one directive per line, chosen to be trivially parseable by
a compiler that is itself going to have to read it on the device with
no line-splitting library to hand:

    version <n>          LIBZ_ABI_VERSION, checked against libz.h
    blob <bytes>         size of libz.bin
    table <offset>       .text offset of libz_table
    patch main <offset>  word to receive main's address
    patch heap <offset>  word to receive the image's _end
    sym <index> <name>   table slot for <name>
"""

import re
import subprocess
import sys


def main():
    if len(sys.argv) != 5:
        sys.stderr.write(
            "usage: mksyms.py <nm> <libz.elf> <libz_table.def> <out.syms>\n")
        return 1

    nm, elf, tabledef, out = sys.argv[1:]

    syms = {}
    for line in subprocess.check_output([nm, elf], text=True).splitlines():
        parts = line.split()
        if len(parts) == 3:
            syms[parts[2]] = int(parts[0], 16)

    for required in ("libz_table", "libz_main_ptr", "libz_heap_start",
                     "libz_header", "_libz_end"):
        if required not in syms:
            sys.stderr.write("mksyms: %s is missing from %s\n" % (required, elf))
            return 1

    base = 0x80000000

    # The order in libz_table.def IS the index assignment. Parsed from
    # the .def rather than from nm, because nm sorts by address and the
    # table's order is the one thing that must not be inferred.
    names = re.findall(r"LIBZ_ENTRY\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)",
                       open(tabledef).read())
    if not names:
        sys.stderr.write("mksyms: no entries found in %s\n" % tabledef)
        return 1

    version = None
    for line in open("libz.h"):
        m = re.match(r"\s*#define\s+LIBZ_ABI_VERSION\s+(\d+)", line)
        if m:
            version = int(m.group(1))
    if version is None:
        sys.stderr.write("mksyms: no LIBZ_ABI_VERSION in libz.h\n")
        return 1

    with open(out, "w") as f:
        f.write("# generated by mksyms.py -- do not edit\n")
        f.write("version %d\n" % version)
        f.write("blob %d\n" % (syms["_libz_end"] - base))
        f.write("table %d\n" % (syms["libz_table"] - base))
        f.write("patch main %d\n" % (syms["libz_main_ptr"] - base))
        f.write("patch heap %d\n" % (syms["libz_heap_start"] - base))
        for i, name in enumerate(names):
            f.write("sym %d %s\n" % (i, name))

    sys.stderr.write("libz: %d entries, blob %d bytes, abi %d\n"
                     % (len(names), syms["_libz_end"] - base, version))
    return 0


if __name__ == "__main__":
    sys.exit(main())
