#!/usr/bin/env python3
# Regenerates handshake_kat.h for test_handshake.c: a whole zfed handshake
# (docs/fed.md, "Sessions, exactly") recomputed independently -- X25519
# and Ed25519 by `cryptography`, ML-KEM-768 by kyber-py, HMAC by hashlib
# -- from the fixed randomness test_handshake.c makes fsess use.
#
#   python3 gen_handshake_kat.py > handshake_kat.h
#
# The session keys must come out the same. That is the only test that
# notices if either secret -- X25519's or ML-KEM's -- were left out of
# them: tampering tests break sessions through the transcript hash either
# way, and a handshake missing one secret still works perfectly.
import hashlib, hmac
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives import serialization
from kyber_py.ml_kem import ML_KEM_768 as K

def stream(a, n): return bytes(((i * 167 + 13) & 255) for i in range(a, a + n))
raw = lambda k: k.public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
# the order fsess takes randomness in: I's X25519 key, I's ML-KEM coins,
# R's X25519 key, then R's ML-KEM message
i_eph, coins, r_eph, km = stream(0, 32), stream(32, 64), stream(96, 32), stream(128, 32)
i_pk = raw(Ed25519PrivateKey.from_private_bytes(bytes([0x11] * 32)).public_key())
i_x, r_x = X25519PrivateKey.from_private_bytes(i_eph), X25519PrivateKey.from_private_bytes(r_eph)
ek, dk = K._keygen_internal(coins[:32], coins[32:])
ss, ct = K._encaps_internal(ek, km)
m0 = b"ZFED1" + i_pk + raw(i_x.public_key()) + ek
m1 = b"ZFED1" + raw(r_x.public_key()) + ct
th = hashlib.sha256(b"zfed handshake 1" + m0 + m1).digest()
dh = i_x.exchange(r_x.public_key())
prk = hmac.new(th, dh + ss, hashlib.sha256).digest()
i2r = hmac.new(prk, b"zfed i2r\x01", hashlib.sha256).digest()
r2i = hmac.new(prk, b"zfed r2i\x01", hashlib.sha256).digest()
def arr(n, b): return "static const uint8_t %s[%d] = { %s };" % (n, len(b), ", ".join("0x%02x" % x for x in b))
print("// generated by gen_handshake_kat.py -- do not edit")
print(arr("kat_m0_sha256", hashlib.sha256(m0).digest()))
print(arr("kat_m1_sha256", hashlib.sha256(m1).digest()))
print(arr("kat_th", th))
print(arr("kat_i2r", i2r))
print(arr("kat_r2i", r2i))
