#!/usr/bin/env python3
# Known answers for sealed letters (core/fmail.c; docs/fed.md, "Mail
# between nodes"), computed again from nothing but the description:
# X25519 and ChaCha20-Poly1305 by `cryptography`, ML-KEM-768 by kyber-py,
# HMAC-SHA256 by hashlib, HChaCha20 (for XChaCha) here, from RFC 7539's
# quarter round.
#
#   python3 gen_mail_kat.py > mail_kat.h
import hashlib, hmac, struct, sys
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey, X25519PublicKey
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from cryptography.hazmat.primitives import serialization
from kyber_py.ml_kem import ML_KEM_768 as K

def H(key, *parts):
    return hmac.new(key, b"".join(parts), hashlib.sha256).digest()

def x_pub(sk):
    return X25519PrivateKey.from_private_bytes(sk).public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw)

def x_dh(sk, pk):
    return X25519PrivateKey.from_private_bytes(sk).exchange(X25519PublicKey.from_public_bytes(pk))

def rotl(v, c): return ((v << c) & 0xffffffff) | (v >> (32 - c))
def qr(s, a, b, c, d):
    s[a] = (s[a] + s[b]) & 0xffffffff; s[d] = rotl(s[d] ^ s[a], 16)
    s[c] = (s[c] + s[d]) & 0xffffffff; s[b] = rotl(s[b] ^ s[c], 12)
    s[a] = (s[a] + s[b]) & 0xffffffff; s[d] = rotl(s[d] ^ s[a], 8)
    s[c] = (s[c] + s[d]) & 0xffffffff; s[b] = rotl(s[b] ^ s[c], 7)

def hchacha20(key, n16):
    s = [0x61707865, 0x3320646e, 0x79622d32, 0x6b206574] + list(struct.unpack("<8I", key)) + list(struct.unpack("<4I", n16))
    for _ in range(10):
        qr(s, 0, 4, 8, 12); qr(s, 1, 5, 9, 13); qr(s, 2, 6, 10, 14); qr(s, 3, 7, 11, 15)
        qr(s, 0, 5, 10, 15); qr(s, 1, 6, 11, 12); qr(s, 2, 7, 8, 13); qr(s, 3, 4, 9, 14)
    return struct.pack("<8I", *(s[0:4] + s[12:16]))

def xchacha_seal(key, nonce24, pt, ad):
    sub = hchacha20(key, nonce24[:16])
    return ChaCha20Poly1305(sub).encrypt(b"\0\0\0\0" + nonce24[16:], pt, ad)	# ciphertext, then the tag

def mail_keys(seed):
    prk = H(b"zfed mail keys 1", seed)
    xsk = H(prk, b"x25519\x01")
    d = H(prk, b"ml-kem-768 d\x01")
    z = H(prk, b"ml-kem-768 z\x01")
    ek, dk = K._keygen_internal(d, z)
    return xsk, x_pub(xsk), ek, dk

def seal(letter, xpk, ek, rnd):
    eph_sk, m, nonce = rnd[:32], rnd[32:64], rnd[64:88]
    ss_m, ct = K._encaps_internal(ek, m)
    eph = x_pub(eph_sk)
    ss_x = x_dh(eph_sk, xpk)
    prk = H(b"zfed mail 1", ss_m + ss_x)
    key = H(prk, b"zfed mail key", eph, xpk, b"\x01")
    head = b"ZML1" + eph + ct
    return head + nonce + xchacha_seal(key, nonce, letter, head)

def seal_classical(letter, xpk, rnd):
    eph_sk, nonce = rnd[:32], rnd[32:56]
    eph = x_pub(eph_sk)
    ss_x = x_dh(eph_sk, xpk)
    prk = H(b"zfed mail x 1", ss_x)
    key = H(prk, b"zfed mail key", eph, xpk, b"\x01")
    head = b"ZMX1" + eph
    return head + nonce + xchacha_seal(key, nonce, letter, head)

def carr(name, b):
    out = "static const uint8_t %s[%d] = {" % (name, len(b))
    for i, v in enumerate(b):
        if i % 16 == 0: out += "\n\t"
        out += "0x%02x," % v
    return out + "\n};\n"

seed = bytes(range(1, 33))
xsk, xpk, ek, dk = mail_keys(seed)
letter = b'{"from":"phil","to":"anna","subject":"Hi","body":"A sealed letter."}'
rnd = bytes((i * 7 + 3) & 0xff for i in range(88))
sealed = seal(letter, xpk, ek, rnd)
print("// generated by gen_mail_kat.py -- do not edit")
print(carr("kat_seed", seed) + carr("kat_xpk", xpk) + carr("kat_ek_sha256", hashlib.sha256(ek).digest()))
print(carr("kat_letter", letter) + carr("kat_rnd", rnd) + carr("kat_sealed", sealed))
rnd_x = bytes((i * 11 + 5) & 0xff for i in range(56))
print(carr("kat_rnd_x", rnd_x) + carr("kat_sealed_x", seal_classical(letter, xpk, rnd_x)))
