#!/bin/sh
#
# chip8 -- run the CHIP-8 test suite ROMs headlessly and compare the
# resulting display against tests/goldens.txt.
#
#   ./tests/suite.sh            check against the goldens
#   ./tests/suite.sh --write    regenerate the goldens
#   ./tests/suite.sh --pgm DIR  also write a PGM of each result
#
# Normally invoked as `make -C sw/apps/chip8 suite`.
#
# -- how the ROMs get here --
#
# They are NOT committed. tests/fetch_roms.sh downloads them; if they
# are absent this script exits 77, which is the convention the rest of
# this tree uses for "skipped, not failed" (see sw/apps/hex/tests). A
# machine with no network still builds and still runs the unit tests,
# which are the ones that need no external anything.
#
# -- why hashes and not images --
#
# A golden that is a directory of PGMs is a binary blob nobody reads.
# A golden that is a text file of hashes shows a behaviour change as
# one modified line naming the ROM it happened in. Use --pgm when a
# line does change and you need to see what it looks like now.
#
# -- why each entry ends on a settled screen --
#
# Several of these ROMs animate their menus (the selection bullet
# blinks), so a hash taken while a menu is up depends on which frame
# the run happened to stop at. Every entry below is tuned to end on a
# RESULT screen, which the ROM draws once and then sits on -- most of
# them enter FX0A and stop executing entirely. Verified stable across
# frame counts; if you retune an entry, re-check it at N and N+7.

set -e

ROMS="${ROMS:-$PWD/tests/roms}"
RUNNER="${RUNNER:-/tmp/chip8_run_rom}"
GOLDENS="${GOLDENS:-$PWD/tests/goldens.txt}"

WRITE=0
PGMDIR=""

while [ $# -gt 0 ]; do
	case "$1" in
	--write) WRITE=1 ;;
	--pgm) PGMDIR="$2"; shift ;;
	*) echo "suite.sh: unknown option $1" >&2; exit 2 ;;
	esac
	shift
done

if [ ! -x "$RUNNER" ]; then
	echo "suite.sh: $RUNNER not built" >&2
	exit 2
fi

if [ ! -d "$ROMS" ] || [ -z "$(ls -A "$ROMS" 2>/dev/null)" ]; then
	echo "suite.sh: no ROMs in $ROMS -- run tests/fetch_roms.sh (skipping)"
	exit 77
fi

[ -n "$PGMDIR" ] && mkdir -p "$PGMDIR"

# name|rom|arguments
#
# The key presses walk each ROM's menus. They are hex key numbers, so
# "-P 2@200" is the key labelled 2 pressed at frame 200 and released
# eight frames later.
SUITE='
chip8-logo|1-chip8-logo.ch8|-p chip8 -c 30 -f 600
ibm-logo|2-ibm-logo.ch8|-p chip8 -c 30 -f 600
corax+|3-corax+.ch8|-p chip8 -c 30 -f 600
flags|4-flags.ch8|-p chip8 -c 30 -f 600
quirks-chip8|5-quirks.ch8|-p chip8 -c 30 -f 800 -P 1@200
quirks-schip|5-quirks.ch8|-p schip -c 30 -f 800 -P 2@200 -P 1@500
quirks-xochip|5-quirks.ch8|-p xochip -c 30 -f 800 -P 3@200
scroll-schip-lores|8-scrolling.ch8|-p schip -c 30 -f 2000 -P 1@200 -P 1@400 -P 1@600
scroll-xochip-lores|8-scrolling.ch8|-p xochip -c 30 -f 2000 -P 1@200 -P 1@400 -P 2@600
'

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

fails=0
run=0
missing=0

# Split on NEWLINES only. The default IFS includes spaces, and every
# entry below has spaces in its argument field -- with the default the
# loop iterates over fragments of each line rather than over lines,
# which presents as run_rom being handed "-q" as a profile name.
OLDIFS=$IFS
IFS='
'

for line in $SUITE; do

	name=$(echo "$line" | cut -d'|' -f1)
	rom=$(echo "$line" | cut -d'|' -f2)
	args=$(echo "$line" | cut -d'|' -f3)

	if [ ! -f "$ROMS/$rom" ]; then
		echo "MISS $name ($rom not downloaded)"
		missing=$((missing + 1))
		continue
	fi

	# IFS is newline-only in this loop (see above), so restore the
	# default around the call -- $args must word-split on spaces to
	# become separate arguments.
	IFS=$OLDIFS
	if [ -n "$PGMDIR" ]; then
		# shellcheck disable=SC2086
		hash=$("$RUNNER" $args -q -s 8 -o "$PGMDIR/$name.pgm" "$ROMS/$rom")
	else
		# shellcheck disable=SC2086
		hash=$("$RUNNER" $args -q "$ROMS/$rom")
	fi
	IFS='
'

	run=$((run + 1))
	printf '%s %s\n' "$name" "$hash" >> "$TMP"

	if [ "$WRITE" = "1" ]; then
		echo "  $name $hash"
		continue
	fi

	want=$(awk -v n="$name" '$1 == n { print $2 }' "$GOLDENS" 2>/dev/null)

	if [ -z "$want" ]; then
		echo "NEW  $name $hash (no golden -- run with --write)"
		fails=$((fails + 1))
	elif [ "$want" = "$hash" ]; then
		echo "ok   $name $hash"
	else
		echo "FAIL $name got $hash wanted $want"
		fails=$((fails + 1))
	fi

done

IFS=$OLDIFS

if [ "$WRITE" = "1" ]; then
	{
		echo "# chip8 test-suite display hashes -- generated by tests/suite.sh --write"
		echo "#"
		echo "# One line per entry. A changed line means the emulated display"
		echo "# changed; re-run with --pgm to see how before accepting it."
		sort "$TMP"
	} > "$GOLDENS"
	echo "wrote $GOLDENS ($run entries)"
	exit 0
fi

[ "$missing" -gt 0 ] && echo "($missing entries skipped -- ROMs not present)"

if [ "$fails" -gt 0 ]; then
	echo "FAILED: $fails of $run"
	exit 1
fi

echo "ok: $run suite ROMs match"
exit 0
