#!/usr/bin/env python3
# Regenerates ed25519_edge.h for test_z25519_hw.cpp.
#
#   python3 gen_ed25519_edge.py > ed25519_edge.h
#
# Inputs, not verdicts: the test asks Monocypher (the reference every
# zfed node without the block uses) for each verdict at run time, and
# requires z_ed25519_check() to agree -- nodes must agree on what is a
# valid signature. The curve arithmetic here is RFC 8032's own reference
# code, independent of both.
import random, hashlib
random.seed(20260927)
p = 2**255 - 19
L = 2**252 + 27742317777372353535851937790883648493
d = -121665 * pow(121666, -1, p) % p
I = pow(2, (p - 1) // 4, p)
def inv(x): return pow(x, p - 2, p)
def add(P, Q):
    A = (P[1]-P[0]) * (Q[1]-Q[0]) % p; B = (P[1]+P[0]) * (Q[1]+Q[0]) % p
    C = 2 * P[3] * Q[3] * d % p; D = 2 * P[2] * Q[2] % p
    E, F, G, H = B-A, D-C, D+C, B+A
    return (E*F % p, G*H % p, F*G % p, E*H % p)
def mul(s, P):
    Q = (0, 1, 1, 0)
    while s > 0:
        if s & 1: Q = add(Q, P)
        P = add(P, P); s >>= 1
    return Q
def recover_x(y, sign):
    if y >= p: return None
    x2 = (y*y - 1) * inv(d*y*y + 1)
    if x2 == 0: return None if sign else 0
    x = pow(x2, (p + 3) // 8, p)
    if (x*x - x2) % p != 0: x = x * I % p
    if (x*x - x2) % p != 0: return None
    if (x & 1) != sign: x = p - x
    return x
def decompress(s):
    y = int.from_bytes(s, "little"); sign = y >> 255; y &= (1 << 255) - 1
    x = recover_x(y, sign)
    return None if x is None else (x, y, 1, x*y % p)
def compress(P):
    zi = inv(P[2]); x = P[0]*zi % p; y = P[1]*zi % p
    return int.to_bytes(y | ((x & 1) << 255), 32, "little")
Gy = 4 * inv(5) % p
G = (recover_x(Gy, 0), Gy, 1, recover_x(Gy, 0) * Gy % p)
def sha512_int(b): return int.from_bytes(hashlib.sha512(b).digest(), "little")
def keypair(secret):
    h = hashlib.sha512(secret).digest()
    a = int.from_bytes(h[:32], "little"); a &= (1 << 254) - 8; a |= 1 << 254
    return a, h[32:], compress(mul(a, G))
def sign(secret, msg):
    a, prefix, A = keypair(secret)
    r = sha512_int(prefix + msg) % L
    R = compress(mul(r, G))
    h = sha512_int(R + A + msg) % L
    s = (r + h * a) % L
    return A, R, s

# the eight small-order points
small = {}
while len(small) < 8:
    P = decompress(bytes(random.randrange(256) for _ in range(32)))
    if P is None: continue
    Q = mul(L, P)
    small[compress(Q)] = Q
small = list(small.values())

rows = []   # (A bytes, msg, R bytes, s int)
def row(A, msg, R, s): rows.append((A, msg, R, s))
for k in range(24):
    sec = bytes(random.randrange(256) for _ in range(32))
    msg = bytes(random.randrange(256) for _ in range(random.choice((0, 1, 32, 44, 100))))
    A, R, s = sign(sec, msg)
    row(A, msg, R, s)                                   # valid
    T = small[k % 8]
    row(A, msg, compress(add(decompress(R), T)), s)       # R + small order: cofactored accepts
    row(A, msg, R, s + L if s + L < 2**256 else s)        # s >= L
    row(A, msg, R, L)                                    # s = L
    bad = bytearray(R); bad[random.randrange(32)] ^= 1 << random.randrange(8); row(A, msg, bytes(bad), s)
    bad = bytearray(A); bad[random.randrange(32)] ^= 1 << random.randrange(8); row(bytes(bad), msg, R, s)
    row(A, msg + b"x", R, s)
# small-order keys and R, s = 0 (and s = 1)
for i in range(8):
    for j in range(8):
        if (i + j) % 3 == 0:
            row(compress(small[i]), b"small", compress(small[j]), 0)
            row(compress(small[i]), b"small", compress(small[j]), 1)
# non-canonical encodings: y = 0 as y = p, y = 1 as y = p + 1, sign bits on x = 0
nc = [int.to_bytes(p, 32, "little"), int.to_bytes(p + 1, 32, "little"),
      int.to_bytes(1 | (1 << 255), 32, "little"), int.to_bytes((p - 1) | (1 << 255), 32, "little"),
      int.to_bytes(p | (1 << 255), 32, "little")]
for a in nc:
    for r in nc:
        row(a, b"nc", r, 0)
sec = bytes(range(32)); msg = b"nc-valid"
A, R, s = sign(sec, msg)
for r in nc: row(A, msg, r, s)
for a in nc: row(a, msg, R, s)
# random 32-byte A and R (about half are points, in the full group)
for k in range(40):
    row(bytes(random.randrange(256) for _ in range(32)), b"rnd",
        bytes(random.randrange(256) for _ in range(32)), random.randrange(L))

def c(b): return "{" + ",".join("0x%02x" % x for x in b) + "}"
print("// generated by gen_ed25519_edge.py -- inputs only; Monocypher gives the verdicts")
print("typedef struct { uint8_t pk[32], sig[64]; uint8_t msg[104]; uint32_t len; } edge_t;")
print("static const edge_t edge[] = {")
for A, msg, R, s in rows:
    sig = R + int.to_bytes(s % 2**256, 32, "little")
    m = msg + bytes(104 - len(msg))
    print("  {%s,%s,%s,%d}," % (c(A), c(sig), c(m), len(msg)))
print("};")
# constants for z25519.c, as 8 little-endian 32-bit limbs
def limbs(v): return "{ " + ", ".join("0x%08xu" % ((v >> (32*i)) & 0xFFFFFFFF) for i in range(8)) + " }"
print("// constants (checked against z25519.c by the test)")
print("static const uint32_t k_d[8] = %s;" % limbs(d))
print("static const uint32_t k_d2[8] = %s;" % limbs(2*d % p))
print("static const uint32_t k_sqrtm1[8] = %s;" % limbs(I))
print("static const uint32_t k_bx[8] = %s;" % limbs(G[0]))
print("static const uint32_t k_by[8] = %s;" % limbs(G[1]))
print("static const uint32_t k_L[8] = %s;" % limbs(L))
