#!/usr/bin/env python3
"""
Generates sw/common/zfont_data.c from the .mem font sources in
sw/data/font/. Not built/run automatically -- re-run by hand and
commit the regenerated zfont_data.c if a font source changes or a new
one is added.

Supports two .mem formats found in sw/data/font/:
  - "flat": N*H lines of W bits each, glyphs in order starting at
    Z_FONT_FIRST (0x20), no separators (font16.mem).
  - "commented": glyphs introduced by a "// Char <codepoint> (<c>)"
    line followed by H lines of W bits each; codepoints need not be
    contiguous (font6x12.mem).
"""

import re
import sys

FIRST = 0x20
LAST = 0x7F  # inclusive; missing codepoints in this range are blank


def pack_row(bits):
    byte = 0
    for i, b in enumerate(bits):
        if b == '1':
            byte |= (1 << (7 - i))
    return byte


def parse_flat(path, w, h):
    with open(path) as f:
        lines = [l.split() for l in f if l.strip()]
    n = len(lines) // h
    glyphs = {}
    for g in range(n):
        rows = []
        for r in range(h):
            bits = lines[g * h + r]
            assert len(bits) == w, f'{path}: expected {w} bits, got {len(bits)}'
            rows.append(pack_row(bits))
        # font16.mem lists rows top-to-bottom already (verified against
        # asymmetric glyphs like 'P'/'b') -- no reversal needed here,
        # unlike the commented format below.
        glyphs[FIRST + g] = rows
    return glyphs


def parse_commented(path, w, h):
    glyphs = {}
    cur = None
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            m = re.match(r'// Char (\d+)', line)
            if m:
                if cur is not None:
                    assert len(rows) == h, f'{path}: char {cur} had {len(rows)} rows'
                    glyphs[cur] = rows[::-1]
                cur = int(m.group(1))
                rows = []
                continue
            bits = line.split()
            assert len(bits) == w, f'{path}: line {line!r} has {len(bits)} bits'
            rows.append(pack_row(bits))
        if cur is not None:
            assert len(rows) == h
            glyphs[cur] = rows[::-1]
    return glyphs


def emit_font(out, name, w, h, glyphs):
    n = LAST - FIRST + 1
    out.write(f'static const uint8_t {name}_data[{n} * {h}] = {{\n')
    for g in range(FIRST, LAST + 1):
        rows = glyphs.get(g, [0] * h)
        ch = chr(g) if 0x21 <= g <= 0x7E else ('space' if g == 0x20 else '?')
        if ch == '\\':
            ch = 'backslash'
        out.write('\t' + ', '.join(f'0x{b:02x}' for b in rows) + f', // 0x{g:02x} {ch}\n')
    out.write('};\n\n')
    out.write(f'const z_font_t {name} = {{ {w}, {h}, 0x{FIRST:02x}, 0x{LAST:02x}, {name}_data }};\n\n')


def main():
    fonts = [
        ('z_font_8x16', 'sw/data/font/font16.mem', 8, 16, parse_flat),
        ('z_font_6x12', 'sw/data/font/font6x12.mem', 6, 12, parse_commented),
    ]

    with open('sw/common/zfont_data.c', 'w') as out:
        out.write('/* Generated by sw/data/font/gen_font_data.py -- do not hand-edit. */\n')
        out.write('/* Regenerate if a .mem source in sw/data/font/ changes. */\n\n')
        out.write('#include <stdint.h>\n#include "zfont.h"\n\n')
        for name, path, w, h, parser in fonts:
            glyphs = parser(path, w, h)
            emit_font(out, name, w, h, glyphs)

    print('wrote sw/common/zfont_data.c')


if __name__ == '__main__':
    main()
