#!/usr/bin/env python3
"""
Generates sw/os/logo_data.c from zeitlos.bin (the raw XBM bit data,
extracted from zeitlos.xbm via xbmtobit.c in this same directory).
Same generator-script pattern sw/data/font/gen_font_data.py uses for
font glyph data -- see sw/os/logo.h for the format this produces.

Usage:
    python3 gen_logo_data.py
"""

from pathlib import Path

IMG_DIR = Path(__file__).parent
BIN_FILE = IMG_DIR / "zeitlos.bin"
OUT_FILE = IMG_DIR.parent.parent / "os" / "logo_data.c"

EXPECTED_SIZE = 512 * 384 // 8


def main():
	data = BIN_FILE.read_bytes()
	if len(data) != EXPECTED_SIZE:
		raise SystemExit(f"{BIN_FILE}: expected {EXPECTED_SIZE} bytes, got {len(data)}")

	with open(OUT_FILE, "w") as out:
		out.write("/* Generated by sw/data/images/gen_logo_data.py -- do not hand-edit. */\n")
		out.write("/* Regenerate if zeitlos.bin (sw/data/images/) changes. */\n\n")
		out.write("#include <stdint.h>\n")
		out.write('#include "logo.h"\n\n')
		out.write(f"const uint8_t z_boot_logo_data[{len(data)}] = {{\n")
		for i in range(0, len(data), 16):
			chunk = data[i:i + 16]
			line = ", ".join(f"0x{b:02x}" for b in chunk)
			out.write(f"\t{line},\n")
		out.write("};\n")

	print(f"wrote {OUT_FILE} ({len(data)} bytes)")


if __name__ == "__main__":
	main()
