#!/usr/bin/env python3
#
# Zeitlos
# Copyright (c) 2025 Lone Dynamics Corporation. All rights reserved.
#
# Generates sw/apps/info/logo_small.c/.h -- a downscaled Zeitlos logo
# for the info app to blit into its window.
#
# Source is zeitlos.bin in this directory: the 512x384 1bpp logo, in
# the framebuffer's own bit order (pixel x at bit (x & 31) of word
# (x >> 5), LEAST significant bit leftmost -- see sw/common/zbm.h).
# That is the same order the output uses, which is the point: the
# result can go to the screen through z_fb_hw_blit_mem() in a single
# blitter operation, with no per-pixel work anywhere at runtime.
#
# The source is cropped to its ink before scaling -- see the bounding
# box code below for why that matters. The default 96px width keeps the
# wordmark readable in under 300 bytes of .rodata, small enough to
# carry in the app rather than reading the 38400-byte boot splash off
# flash and downscaling it at startup.
#
# USAGE
#
#   python3 gen_logo_small.py [width]
#
#   Re-run if zeitlos.bin changes. The .c/.h it produces are checked
#   in, same convention as gen_dock_icon_data.py and the font data --
#   building the OS needs no Python, only regenerating does.

import sys
import os

SRC_W, SRC_H = 512, 384

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "zeitlos.bin")
OUT_DIR = os.path.join(HERE, "..", "..", "apps", "info")

# Target width in pixels. Must be a multiple of 32 so the generated
# array is a whole number of words and the runtime stride is trivial.
target_w = int(sys.argv[1]) if len(sys.argv) > 1 else 96

if target_w % 32:
    print("error: target width %d is not a multiple of 32" % target_w,
          file=sys.stderr)
    sys.exit(1)

data = open(SRC, "rb").read()
if len(data) != SRC_W * SRC_H // 8:
    print("error: %s is %d bytes, expected %d"
          % (SRC, len(data), SRC_W * SRC_H // 8), file=sys.stderr)
    sys.exit(1)

def src_pixel(x, y):
    # LSB-leftmost within each byte, matching the framebuffer
    bit = y * SRC_W + x
    return (data[bit >> 3] >> (bit & 7)) & 1

# Crop to the ink first.
#
# The source is a full-screen splash: the wordmark occupies a band
# roughly 239x45 in the middle of 512x384, and the rest is empty.
# Scaling the whole thing down spends almost every output row on blank
# space and leaves the wordmark six pixels tall and unreadable. The
# bounding box is found rather than hardcoded so this keeps working if
# the artwork is ever recentred or resized.
x0, y0 = SRC_W, SRC_H
x1, y1 = -1, -1

for y in range(SRC_H):
    for x in range(SRC_W):
        if src_pixel(x, y):
            if x < x0: x0 = x
            if x > x1: x1 = x
            if y < y0: y0 = y
            if y > y1: y1 = y

if x1 < 0:
    print("error: %s has no set pixels" % SRC, file=sys.stderr)
    sys.exit(1)

crop_w = x1 - x0 + 1
crop_h = y1 - y0 + 1

DST_W = target_w
# Preserve the aspect ratio, rounding to at least one row.
DST_H = max(1, round(crop_h * DST_W / crop_w))

words_per_row = DST_W // 32

# Downscale by "any source pixel in the block wins".
#
# NOT majority: the logo is fine strokes, and a majority rule erases
# them almost entirely at this ratio. Any-set keeps the letterforms
# legible, at the cost of thickening them slightly -- which at this
# size reads as bold rather than as an artifact.
rows = []

for dy in range(DST_H):
    sy0 = y0 + (dy * crop_h) // DST_H
    sy1 = y0 + ((dy + 1) * crop_h) // DST_H
    if sy1 <= sy0: sy1 = sy0 + 1
    row = [0] * words_per_row
    for dx in range(DST_W):
        sx0 = x0 + (dx * crop_w) // DST_W
        sx1 = x0 + ((dx + 1) * crop_w) // DST_W
        if sx1 <= sx0: sx1 = sx0 + 1
        on = 0
        for sy in range(sy0, sy1):
            for sx in range(sx0, sx1):
                if src_pixel(sx, sy):
                    on = 1
                    break
            if on:
                break
        if on:
            row[dx >> 5] |= 1 << (dx & 31)
    rows.append(row)

set_px = sum(bin(w).count("1") for r in rows for w in r)

os.makedirs(OUT_DIR, exist_ok=True)

with open(os.path.join(OUT_DIR, "logo_small.h"), "w") as f:
    f.write("""/* Generated by sw/data/images/gen_logo_small.py -- do not hand-edit. */
/* Regenerate if zeitlos.bin changes. */

#ifndef LOGO_SMALL_H
#define LOGO_SMALL_H

#include <stdint.h>

/*
 * The Zeitlos logo, downscaled from the 512x384 original in
 * sw/data/images/zeitlos.bin.
 *
 * Stored in the FRAMEBUFFER's own bit order -- pixel x at bit (x & 31)
 * of word (x >> 5), least significant bit leftmost -- so it reaches
 * the screen through one z_fb_hw_blit_mem() call with no per-pixel
 * work at runtime. Pass Z_LOGO_SMALL_STRIDE as the source stride.
 */

#define Z_LOGO_SMALL_W       %d
#define Z_LOGO_SMALL_H       %d
#define Z_LOGO_SMALL_WORDS   %d
#define Z_LOGO_SMALL_STRIDE  (Z_LOGO_SMALL_WORDS * 4)

extern const uint32_t z_logo_small[Z_LOGO_SMALL_H][Z_LOGO_SMALL_WORDS];

#endif
""" % (DST_W, DST_H, words_per_row))

with open(os.path.join(OUT_DIR, "logo_small.c"), "w") as f:
    f.write("/* Generated by sw/data/images/gen_logo_small.py"
            " -- do not hand-edit. */\n")
    f.write("/* Regenerate if zeitlos.bin changes. */\n\n")
    f.write('#include "logo_small.h"\n\n')
    f.write("const uint32_t z_logo_small"
            "[Z_LOGO_SMALL_H][Z_LOGO_SMALL_WORDS] = {\n")
    for row in rows:
        f.write("\t{ " + ", ".join("0x%08x" % w for w in row) + " },\n")
    f.write("};\n")

print("wrote %s/logo_small.c and logo_small.h (%dx%d, %d bytes, %d pixels set)"
      % (OUT_DIR, DST_W, DST_H, DST_H * words_per_row * 4, set_px))
