/* Generated by sw/data/icons/gen_dock_icon_data.py -- do not hand-edit. */
/* Regenerate if a source PNG in that directory changes or is added. */

#ifndef Z_DOCK_ICONS_H
#define Z_DOCK_ICONS_H

#include <stdint.h>

/*
 * 32x32 1bpp dock icon bitmaps -- see gen_dock_icon_data.py (this
 * file's generator, sw/data/icons/) for the source PNGs and exact
 * format. Each array is 32 rows of 4 bytes, MSB-first, bit 1 = ink.
 * Referenced from wm.c's dock_apps[] table -- see that table's own
 * comment for how to wire a new icon in after regenerating this file.
 */

extern const uint8_t z_icon_calc_data[32 * 4];
extern const uint8_t z_icon_clock_data[32 * 4];
extern const uint8_t z_icon_draw_data[32 * 4];
extern const uint8_t z_icon_files_data[32 * 4];
extern const uint8_t z_icon_gamedemo_data[32 * 4];
extern const uint8_t z_icon_gpu3d_data[32 * 4];
extern const uint8_t z_icon_info_data[32 * 4];
extern const uint8_t z_icon_midi_data[32 * 4];
extern const uint8_t z_icon_play_data[32 * 4];
extern const uint8_t z_icon_read_data[32 * 4];
extern const uint8_t z_icon_settings_data[32 * 4];
extern const uint8_t z_icon_space3d_data[32 * 4];
extern const uint8_t z_icon_term_data[32 * 4];
extern const uint8_t z_icon_text_data[32 * 4];
extern const uint8_t z_icon_track_data[32 * 4];

#endif
